# üè† Riyadh Real Estate Dashboard

## üí° Introdruon
- Riyadh's real estate market is dynamic and rapidly evolving. This project seeks to provide valuable insights into market trends, property prices, and key factors influencing Riyadh's real estate landscape. By leveraging Python's data analysis capabilities and Plotly's interactive visualization tools, we aim to uncover notable patterns and relationships within the data.

<div style="text-align: center;">
  <img src="https://storage.googleapis.com/kaggle-datasets-images/2623149/4482894/1dfb26becf747a0b196a41d51e031964/dataset-cover.jpg?t=2023-08-17-09-58-06" alt="Dataset Cover">
</div>

## üìä Dataset Overview and Source:
- URL link : https://www.kaggle.com/datasets/reemamuhammed/riyadh-villas-aqar, Riyadh Villas Dataset is web scraped from Aqar.sa by **Reema Abuthnain**
- About the Dataset : This dataset contains over 50k villas located in Riyadh, Saudi Arabia. Each villa contains information such as the location, neighborhood, number of bedrooms, number of bathrooms, the space of the villa, and many more!
  
| Column Name    | Definition                                                                                           | Data Type      |
|----------------|------------------------------------------------------------------------------------------------------|----------------|
| front          | Orientation of the property's front side, indicating which direction it faces relative to the street.| object         |
| rooms          | Total count of bedrooms or main living spaces within the property.                                   | int64          |
| lounges        | Number of lounge or relaxation areas available in the property.                                      | object         |
| bathrooms      | Total count of bathrooms included in the property.                                                   | object         |
| streetWidth    | Measurement of the width of the street adjacent to the property.                                     | float64        |
| stairs         | Specifies if the property has staircases and their type, if present.                                 | float64        |
| driverRoom     | Indicates if there is a dedicated room available for drivers.                                        | float64        |
| SunLightRoom   | Presence of a room designed for ample natural sunlight.                                              | float64        |
| kitchen        | Total count of kitchens provided within the property.                                                | float64        |
| outdoorRoom    | Availability of outdoor or open-air spaces connected to the property.                                | float64        |
| garage         | Indicates whether a garage is available for vehicle parking.                                         | float64        |
| duplex         | Specifies if the property structure is a duplex with two separate units.                             | float64        |
| Area           | Total area or size of the property, measured in square units.                                        | int64          |
| apartments     | Number of individual apartment units or living spaces in the property.                               | object         |
| StaffRoom      | Presence of a designated room for staff or household workers.                                        | float64        |
| elevator       | Indicates if an elevator is present within the property.                                             | float64        |
| furnished      | Specifies if the property is offered as fully furnished.                                             | float64        |
| pool           | Indicates the availability of a swimming pool on the property.                                       | float64        |
| basement       | Specifies whether there is a basement or cellar space in the property.                               | float64        |
| neighbourhood  | General description of the surrounding area and neighborhood of the property.                        | object         |
| location       | More detailed information about the specific address or location of the property.                    | object         |
| price          | Listed cost or asking price for purchasing or renting the property.                                  | float64        |
| square_price   | Price per square unit of the property, providing a basis for comparison with other properties.       | float64        |


## üåä Data Flow and Steps:
1. **üìöImport Software Libraries:**
    - Load necessary libraries such as pandas, numpy, matplotlib, seaborn, and Plotly for analysis and visualization.
2. **üìÇRead Dataset**
    - Import the dataset (e.g., CSV, Excel) into a pandas DataFrame for further processing.
3. **üîçData Exploration (EDA)**
    - Explore the data by checking the first few rows, understanding data types, checking for missing values, and generating summary statistics.
4. **üßπData Cleaning and Preprocessing**
    - Handle missing values, duplicate entries, outliers, and correct any inconsistencies in the data.
5. **üìäData Visualization**
    - Use visual techniques (e.g., histograms, scatter plots, box plots) to understand patterns, trends, and distributions in the data.
6. **üîÑChange the Data Types**
    - Convert columns to appropriate data types (e.g., converting strings to datetime, categorical data to category type) for better analysis.
7. **‚úèÔ∏èRename Columns**
    - Rename columns for clarity, readability, or to match the required format for analysis or visualization.
8. **üìàData Analysis & Insights Finding**
    - Perform statistical and analytical techniques (e.g., correlation analysis, groupby operations) to extract meaningful insights.
9. **üöÄBuild and Run the Dashboard using Plotly-Dash**
    - Create an interactive dashboard using Plotly-Dash to visualize and present the results of your analysis dynamically.
10. **üåêDeploy the Dashboard on Render**
    - Deploy the Plotly-Dash app to Render, to make the interactive dashboard accessible and ready to use online.

# Import Software Libraries

In [1]:
# Ignore Warnings:
import warnings
warnings.filterwarnings("ignore")

# Python Libraries:
import os
import re
import random

# Data Manuplatiob Libraries:
import numpy as np
import pandas as pd

# Data Visualization Libraries:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.subplots as sp
import plotly.io as pio
pio.renderers.default = 'iframe'

# Plotly-Dash Libraries:
from jupyter_dash import JupyterDash
import dash_bootstrap_components as dbc
from dash import Dash, dcc, html, Input, Output, State

# Arabic Words Libraries:
import arabic_reshaper
from bidi.algorithm import get_display

# Read the Dataset

In [2]:
df = pd.read_csv('RiyadhVillasAqar.csv', index_col=0)

# Data Exploration (EDA)

In [3]:
df.head()

,front,rooms,lounges,bathrooms,streetWidth,stairs,propertyAge,driverRoom,tent,patio,...,apartments,maidRoom,elevator,furnihsed,pool,basement,neighbourhood,location,price,square price
0,ÿ¥ÿ±ŸÇŸäÿ©,5,4.0,5+,20.0,1.0,0.0,1.0,1.0,1.0,...,0,0.0,0.0,0.0,0.0,0.0,ÿπŸÉÿßÿ∏,ÿ¨ŸÜŸàÿ® ÿßŸÑÿ±Ÿäÿßÿ∂,1050000.0,3500.000000
1,ÿ∫ÿ±ÿ®Ÿäÿ©,4,3.0,5+,20.0,1.0,0.0,1.0,1.0,1.0,...,2.0,1.0,1.0,0.0,0.0,0.0,ÿßŸÑŸÖŸáÿØŸäÿ©,ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂,3000000.0,5555.555556
2,ÿ¨ŸÜŸàÿ®Ÿäÿ© ÿ¥ÿ±ŸÇŸäÿ©,7,2.0,5+,15.0,1.0,31.0,1.0,0.0,1.0,...,0,1.0,0.0,0.0,0.0,0.0,ÿßŸÑÿ¥ŸÅÿß,ÿ¨ŸÜŸàÿ® ÿßŸÑÿ±Ÿäÿßÿ∂,2000000.0,2285.714286
3,ÿ∫ÿ±ÿ®Ÿäÿ©,7,3.0,5+,15.0,1.0,3.0,0.0,1.0,1.0,...,0,1.0,0.0,1.0,0.0,0.0,ÿ∏Ÿáÿ±ÿ© ŸÑÿ®ŸÜ,ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂,894000.0,4470.000000
4,ÿ¥ŸÖÿßŸÑŸäÿ©,4,2.0,4,25.0,1.0,0.0,1.0,1.0,1.0,...,3.0,1.0,1.0,1.0,0.0,0.0,ŸÇÿ±ÿ∑ÿ®ÿ©,ÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂,3500000.0,8750.000000

In [4]:
df.shape

(46826, 25)

In [5]:
df.dtypes

front             object
rooms              int64
lounges           object
bathrooms         object
streetWidth      float64
stairs           float64
propertyAge      float64
driverRoom       float64
tent             float64
patio            float64
kitchen          float64
outdoorRoom      float64
garage           float64
duplex           float64
space              int64
apartments        object
maidRoom         float64
elevator         float64
furnihsed        float64
pool             float64
basement         float64
neighbourhood     object
location          object
price            float64
square price     float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46826 entries, 0 to 51844
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   front          46826 non-null  object
 1   rooms          46826 non-null  int64
 2   lounges        45708 non-null  object
 3   bathrooms      46826 non-null  object
 4   streetWidth    46636 non-null  float64
 5   stairs         46826 non-null  float64
 6   propertyAge    46826 non-null  float64
 7   driverRoom     46826 non-null  float64
 8   tent           46826 non-null  float64
 9   patio          46826 non-null  float64
 10  kitchen        46826 non-null  float64
 11  outdoorRoom    46826 non-null  float64
 12  garage         46826 non-null  float64
 13  duplex         46826 non-null  float64
 14  space          46826 non-null  int64
 15  apartments     46826 non-null  object
 16  maidRoom       46826 non-null  float64
 17  elevator       46826 non-null  float64
 18  furnihsed      46826 non-null  float64
 19  pool           46826 non-null  float64
 20  basement       46826 non-null  float64
 21  neighbourhood  46826 non-null  object
 22  location       46826 non-null  object
 23  price          46824 non-null  float64
 24  square price   46824 non-null  float64
dtypes: float64(17), int64(2), object(6)
memory usage: 9.3+ MB

In [7]:
df.describe()

,rooms,streetWidth,stairs,propertyAge,driverRoom,tent,patio,kitchen,outdoorRoom,garage,duplex,space,maidRoom,elevator,furnihsed,pool,basement,price,square price
count,46826.000000,46636.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,46826.000000,4.682400e+04,46824.000000
mean,4.687439,18.158418,0.683979,2.454790,0.355871,0.466258,0.769380,0.979114,0.645112,0.907872,0.297698,380.021740,0.767821,0.235745,0.078738,0.116410,0.037671,2.347636e+06,6088.058800
std,1.104970,4.167866,0.464926,6.496833,0.478781,0.498866,0.421234,0.143004,0.478485,0.289210,0.457251,281.431272,0.422227,0.424468,0.269333,0.320719,0.190402,2.782053e+06,4515.845244
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.080000e+03,3.428571
25%,4.000000,15.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,270.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.180000e+06,3866.666667
50%,5.000000,20.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,312.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.600000e+06,5000.000000
75%,5.000000,20.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,400.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.600000e+06,7600.000000
max,7.000000,100.000000,1.000000,35.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,10000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+08,136144.578313

In [8]:
df.columns

Index(['front', 'rooms', 'lounges', 'bathrooms', 'streetWidth', 'stairs',
       'propertyAge', 'driverRoom', 'tent', 'patio', 'kitchen', 'outdoorRoom',
       'garage', 'duplex', 'space', 'apartments', 'maidRoom', 'elevator',
       'furnihsed', 'pool', 'basement', 'neighbourhood', 'location', 'price',
       'square price'],
      dtype='object')

In [9]:
for col in list(df.columns):
    print(col, len(list(df[col].value_counts().index)))

front 10
rooms 7
lounges 11
bathrooms 5
streetWidth 55
stairs 2
propertyAge 36
driverRoom 2
tent 2
patio 2
kitchen 2
outdoorRoom 2
garage 2
duplex 2
space 742
apartments 44
maidRoom 2
elevator 2
furnihsed 2
pool 2
basement 2
neighbourhood 295
location 5
price 672
square price 4917

In [10]:
df.isnull().sum()

front               0
rooms               0
lounges          1118
bathrooms           0
streetWidth       190
stairs              0
propertyAge         0
driverRoom          0
tent                0
patio               0
kitchen             0
outdoorRoom         0
garage              0
duplex              0
space               0
apartments          0
maidRoom            0
elevator            0
furnihsed           0
pool                0
basement            0
neighbourhood       0
location            0
price               2
square price        2
dtype: int64

In [11]:
df.isnull().sum().sum()

1312

# Data Cleaning and Preprocessing

#### Clean the values from duplicated same values (1, 2, 2.0, 3, 3.0, etc)

In [12]:
lounge_counts_df = df['lounges'].value_counts().reset_index()
lounge_counts_df.columns = ['Lounge', 'Count']

lounge_counts_df

   Lounge  Count
0       2  15418
1       3  10129
2       1   6259
3     2.0   4301
4     3.0   2863
5       4   2173
6     1.0   1737
7       5   1611
8     4.0    659
9     5.0    545
10     7+     13

In [13]:
df['lounges'] = df['lounges'].str.replace(r'\.0$', '', regex=True)

lounge_counts_df = df['lounges'].value_counts().reset_index()
lounge_counts_df.columns = ['Lounge', 'Count']

lounge_counts_df

  Lounge  Count
0      2  19719
1      3  12992
2      1   7996
3      4   2832
4      5   2156
5     7+     13

In [14]:
apartment_counts_df = df['apartments'].value_counts().reset_index()
apartment_counts_df.columns = ['Apartment', 'Count']

apartment_counts_df

   Apartment  Count
0          0  18946
1        0.0   7863
2          1   4319
3          2   3840
4        1.0   2917
5        2.0   2667
6        1.0   2137
7        2.0   1928
8          3    736
9        3.0    504
10       3.0    463
11         4    153
12       4.0    138
13       4.0    120
14         5     15
15         8      8
16       5.0      8
17       5.0      6
18         6      5
19        12      5
20       6.0      4
21        10      4
22       30+      4
23       6.0      3
24      15.0      3
25      10.0      3
26       7.0      3
27      11.0      2
28        20      2
29      13.0      2
30       7.0      2
31      14.0      2
32        11      2
33         7      2
34      23.0      1
35      13.0      1
36       8.0      1
37        15      1
38        14      1
39        23      1
40      16.0      1
41      15.0      1
42         9      1
43      12.0      1

In [15]:
df['apartments'] = df['apartments'].astype(str).str.replace(r'\.0$', '', regex=True)
df['apartments'] = df['apartments'].replace('nan', None)

apartment_counts_df = df['apartments'].value_counts(dropna=False).reset_index()
apartment_counts_df.columns = ['Apartment', 'Count']

apartment_counts_df

   Apartment  Count
0          0  26809
1          1   9373
2          2   8435
3          3   1703
4          4    411
5          5     29
6          6     12
7          8      9
8          7      7
9         10      7
10        12      6
11        15      5
12        11      4
13       30+      4
14        13      3
15        14      3
16        23      2
17        20      2
18         9      1
19        16      1

#### Remove and Deal with NaN values

In [16]:
df.isnull().sum()

front               0
rooms               0
lounges          1118
bathrooms           0
streetWidth       190
stairs              0
propertyAge         0
driverRoom          0
tent                0
patio               0
kitchen             0
outdoorRoom         0
garage              0
duplex              0
space               0
apartments          0
maidRoom            0
elevator            0
furnihsed           0
pool                0
basement            0
neighbourhood       0
location            0
price               2
square price        2
dtype: int64

In [17]:
mode_lounges = df['lounges'].mode()[0]
df['lounges'] = df['lounges'].fillna(mode_lounges)

In [18]:
df['streetWidth'] = df['streetWidth'].fillna(int(df['streetWidth'].mean()))

In [19]:
df.dropna(axis=0, inplace = True)

In [20]:
df.isnull().sum().sum()

0

In [21]:
df.shape

(46824, 25)

#### Drop Duplicated Rows

In [22]:
df.duplicated().sum()

15640

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.duplicated().sum()

0

In [25]:
df.shape

(31184, 25)

#### Clean neighbourhood column

In [26]:
neighbourhood_counts_df = df['neighbourhood'].value_counts().reset_index()
neighbourhood_counts_df.columns = ['Neighbourhood', 'Count']

neighbourhood_counts_df

    Neighbourhood  Count
0           ÿ∑ŸàŸäŸÇ    5105
1         ÿßŸÑÿ±ŸÖÿßŸÑ    2764
2         ÿßŸÑŸÜÿ±ÿ¨ÿ≥    2066
3           ÿπŸÉÿßÿ∏    2030
4            ÿ®ÿØÿ±    1841
..            ...    ...
290    Ÿâ ÿßŸÑŸàÿßÿ≥ÿ∑Ÿä       1
291           ÿ±Ÿä       1
292  ÿØÿ±Ÿá ÿßŸÑÿ™ŸàŸÜÿ≥Ÿä       1
293     Ÿâ ÿßŸÑŸÅÿ±ÿ∂Ÿä       1
294           ÿßÿµ       1

[295 rows x 2 columns]

In [27]:
for neighbourhood in list(neighbourhood_counts_df['Neighbourhood']):
    print(neighbourhood)

 ÿ∑ŸàŸäŸÇ
 ÿßŸÑÿ±ŸÖÿßŸÑ
 ÿßŸÑŸÜÿ±ÿ¨ÿ≥
 ÿπŸÉÿßÿ∏
 ÿ®ÿØÿ±
 ÿßŸÑÿπÿßÿ±ÿ∂
 ÿßŸÑŸÖŸàŸÜÿ≥Ÿäÿ©
 ÿßŸÑŸÖŸÑŸÇÿß
 ÿßŸÑŸÖŸáÿØŸäÿ©
 ÿßŸÑÿ≠ÿ≤ŸÖ
 ÿßŸÑŸäÿßÿ≥ŸÖŸäŸÜ
 ÿßŸÑŸÜŸáÿ∂ÿ©
 ÿ∏Ÿáÿ±ÿ© ŸÑÿ®ŸÜ
 ÿßŸÑÿØÿßÿ± ÿßŸÑÿ®Ÿäÿ∂ÿßÿ°
 ÿ∑Ÿäÿ®ÿ©
 ÿßŸÑŸÇÿßÿØÿ≥Ÿäÿ©
 ÿßŸÑÿπÿ≤Ÿäÿ≤Ÿäÿ©
 ÿßŸÑÿÆŸÑŸäÿ¨
 ÿßÿ¥ÿ®ŸäŸÑŸäÿ©
 ŸÇÿ±ÿ∑ÿ®ÿ©
 ÿßŸÑŸäÿ±ŸÖŸàŸÉ
 ŸÖÿ∑ÿßÿ± ÿßŸÑŸÖŸÑŸÉ ÿÆÿßŸÑÿØ ÿßŸÑÿØŸàŸÑŸä
 ÿßŸÑÿ¨ŸÜÿßÿØÿ±Ÿäÿ©
 ÿßŸÑÿ≥ŸàŸäÿØŸä
 ÿßŸÑÿ¥ŸÅÿß
 ÿØŸäÿ±ÿßÿ®
 ÿ≠ÿ∑ŸäŸÜ
 ÿßŸÑÿ±ŸÖÿßŸÑ
 ÿßŸÑŸÜÿÆŸäŸÑ
 ÿ∏Ÿáÿ±ÿ© ŸÜŸÖÿßÿ±
 ÿßŸÑÿ≥ÿπÿßÿØÿ©
 ÿßŸÑŸÇŸäÿ±ŸàÿßŸÜ
 ÿßŸÑÿµÿ≠ÿßŸÅÿ©
 ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑÿ∫ÿ±ÿ®Ÿäÿ©
 ÿßŸÑŸÜÿØŸâ
 ÿ∏Ÿáÿ±ÿ© ÿßŸÑÿ®ÿØŸäÿπÿ©
 ÿßŸÑÿ®ŸäÿßŸÜ
 ÿßŸÑÿπŸÇŸäŸÇ
 ÿßŸÑÿ≠ŸÖÿ±ÿßÿ°
 ÿßŸÑŸàÿßÿØŸä
 ÿßŸÑÿ±Ÿàÿ∂ÿ©
 ÿßŸÑÿπŸÑŸäÿß
 ÿßŸÑÿ≤Ÿáÿ±ÿ©
 ÿßŸÑŸÖŸÑŸÉ ŸÅŸáÿØ
 ÿßŸÑŸÖÿ≠ŸÖÿØŸäÿ©
 ÿßŸÑŸÖÿπŸäÿ≤ŸäŸÑÿ©
 ÿßŸÑŸÜÿØŸàÿ©
 ÿßŸÑÿ¥ÿ±ŸÇ
 ÿßŸÑŸÜÿ≥ŸäŸÖ ÿßŸÑÿ∫ÿ±ÿ®Ÿä
 ÿßŸÑÿ±ÿ®Ÿäÿπ
 ÿßŸÑŸÇÿØÿ≥
ÿ© ŸÜŸÖÿßÿ±
 ÿπÿ±ŸÇÿ©
 ÿßŸÑÿßŸÜÿØŸÑÿ≥
 ÿßŸÑŸÖÿµŸäŸÅ
 ŸÜŸÖÿßÿ±
 ÿßŸÑŸÖŸÑÿ≤
 ÿßŸÑŸÖÿ±Ÿàÿ¨
 ÿßŸÑÿ∫ÿØŸäÿ±
 ÿ≥ŸÑÿ∑ÿßŸÜÿ©
 ÿßŸÑÿ≥ŸÑŸäŸÖÿßŸÜŸäÿ©
 ÿ£ÿ≠ÿØ
 ÿ∫ÿ±ŸÜÿßÿ∑ÿ©
 ÿßŸÑŸÜŸÅŸÑ
 ÿ¥ÿ®ÿ±ÿß
 ÿßŸÑŸàÿ±ŸàÿØ
 ÿßŸÑÿ±Ÿàÿßÿ®Ÿä
 ÿßŸÑÿ±ÿ®Ÿàÿ©
 ÿßŸÑŸÜÿ≤Ÿáÿ©
 ÿßŸÑÿ±ŸäÿßŸÜ
 ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑŸàÿ≥ÿ∑Ÿâ
 ÿßÿ≠ÿØ
 ÿßŸÑŸÜÿ∏ŸäŸÖ
 ÿßŸÑÿ™ÿπÿßŸàŸÜ
 ÿßŸÑŸÜÿ≥ŸäŸÖ ÿßŸÑÿ¥ÿ±ŸÇŸä
 ÿßŸÑŸÖÿ±ÿ≥ŸÑÿßÿ™
 ÿßŸÑŸÅŸÑÿßÿ≠
 ÿßŸÑŸÅŸäÿ≠ÿßÿ°
 ÿßŸÑÿ±ÿ≠ŸÖÿßŸÜŸäÿ©
 ÿßŸÑŸÖŸÑŸÉ ŸÅŸäÿµŸÑ
 ÿßŸÑÿØÿ±ŸäŸáŸÖŸäÿ©
 ÿßŸÑÿßÿ≤ÿØŸáÿßÿ±
ŸÖ ŸÇÿßÿ∂Ÿä
 ÿßŸÑŸÖÿ±Ÿàÿ©
 ÿßŸÑŸÅÿßÿ±ŸàŸÇ
Ÿâ ÿßŸÑÿπÿµÿßŸÖŸä
 ÿßŸÑŸÖŸÜÿßÿ±
 ÿßŸÑŸÜÿ±ÿ¨ÿ≥
 ÿßŸÑÿ¨ÿ≤Ÿäÿ±ÿ©
 ÿ®ÿØÿ±
 ÿßŸÑÿ≥ŸÑÿßŸÖ
 ÿßŸÑÿ®ÿØŸäÿπÿ©
 ÿßŸÑŸàÿßÿ≠ÿ©
ÿ©
 ÿßŸÑÿ≥ŸàŸäÿØŸä ÿßŸÑÿ∫ÿ±ÿ®Ÿä
 ÿßŸÑÿ¥ŸáÿØÿßÿ°
Ÿä ÿßŸÑÿØŸäŸÜ ÿßŸÑÿ®ÿ∫ŸàŸä
 ÿßŸÑŸÖŸÑŸÉ ÿπÿ®ÿØÿßŸÑŸÑŸá
 ÿßŸÑŸÖÿ∫ÿ±ÿ≤ÿßÿ™
ŸÖŸä
 Ÿáÿ¨ÿ±ÿ© ŸÑÿ®ŸÜ
 ÿßŸÑŸÖŸÜÿµŸàÿ±ÿ©
ŸÖ ÿßŸÑÿ≠ÿ±ŸäŸÖŸä
 ÿßŸÑŸÅÿßÿÆÿ±Ÿäÿ©
 ÿßŸÑÿπŸàÿßŸÑŸä
 ÿßŸÑŸäŸÖÿßŸÖÿ©
ÿ±ÿßÿ™
 ÿßŸÑÿÆÿßŸÑÿØŸäÿ©
 ÿµŸÑÿßÿ≠ ÿßŸÑÿØŸäŸÜ
ŸÖ ÿ®ŸÜ ÿßŸÑŸÇÿßÿ®ŸÑÿ©
 ÿßŸÑÿÆŸäÿ±
 ÿ¨ÿ±Ÿäÿ±
Ÿä ÿ®ŸÜ ÿπÿØŸä
Ÿâ ÿßŸÑÿ∞ŸÖÿßÿ±Ÿä
Ÿâ ÿßŸÑÿ∑ÿßÿ¶Ÿä
 ÿ£ŸÖ ÿßŸÑÿ≠ŸÖÿßŸÖ ÿßŸÑÿ∫ÿ±ÿ®Ÿä
 ÿßŸÑÿßÿ≥ŸÉÿßŸÜ
 ÿßŸÑÿ≠ÿ≤ŸÖ
 ÿßŸÑÿ∫ŸÜÿßŸÖŸäÿ©
Ÿá ÿ®ŸÜ ÿÆŸÑŸäŸÅŸá
 ÿßŸÑÿ≠ÿßÿ¶ÿ±
Ÿâ
Ÿâ ÿ®ŸÜ ŸäŸâ ÿßŸÑŸÇÿ±ÿ∑ÿ®Ÿä
Ÿâ ÿßŸÑÿ£ÿ≤ÿØŸä
Ÿâ ÿ®ŸÜ ÿßŸÑŸÇÿßÿ≥ŸÖ
 ÿßŸÑÿ∂ÿ®ÿßÿ∑
 ÿßŸÑŸÖÿµÿßŸÜÿπ
ŸÖ
 ÿßŸÑŸÖŸÜÿµŸàÿ±Ÿäÿ©
 ÿπÿ±Ÿäÿ∂
ŸàŸÜ
 ÿßŸÑŸÖÿπÿ∞ÿ± ÿßŸÑÿ¥ŸÖÿßŸÑŸä
 ÿßŸÑÿßŸÜÿ≥Ÿä
 ÿπŸÉÿßÿ∏
 ŸÑÿ®ŸÜ
 ÿßŸÑÿÆÿ≤ÿßŸÖŸâ
ÿßŸÜ ÿ®ŸÜ ÿπÿ®ÿØÿßŸÑŸÑŸá
Ÿâ ÿ®ŸÜ ÿÆÿßŸÑÿØ ÿßŸÑÿ®ÿ±ŸÖŸÉŸä
Ÿâ ÿ®ŸÜ ÿ¨ÿ≤ŸÑÿ©
Ÿâ ÿßŸÑŸÖŸÅÿ™Ÿä
 ŸÉŸÖÿßŸÑ
 ÿßŸÑŸÖÿ±ÿ®ÿπ
Ÿâ ÿ®ŸÜ ÿπÿ®ÿØÿßŸÑÿπÿ≤Ÿäÿ≤
 ÿßŸÑÿµŸÅÿß
 ÿßŸÑÿ±ÿßÿ¶ÿØ
ÿ±ÿ©
Ÿâ ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ®
Ÿâ ÿßŸÑÿ™ŸäŸÖŸä
Ÿâ ÿßŸÑÿ∑ÿßŸÑÿ®Ÿä
Ÿâ ÿ®ŸÜ ÿßŸÉÿ´ŸÖ
 ÿßŸÑŸÉÿ™ÿßŸÜŸä
Ÿâ ÿßŸÑÿßŸÜÿ≥Ÿä
ŸÖ ÿßŸÑŸÖÿ∫ÿ±ÿ®Ÿä
ÿßŸÜ
Ÿá
ÿØ
ÿ∑
Ÿâ ÿ®ŸÜ ÿπÿ®ŸäÿØ
ÿØŸá ÿ®ŸÜ ŸÖÿπÿßŸàŸäŸá
Ÿâ ÿßŸÑŸÖÿØŸÜŸä
Ÿâ ÿ®ŸÜ ŸÖÿ≥ÿπŸàÿØ
 ÿπŸÇÿ±ÿ®ÿßÿ°
 ÿπÿ™ŸäŸÇÿ©
ÿßŸÜŸä
Ÿâ ÿ®ŸÜ ŸÇÿ≤ÿπÿ© ÿßŸÑŸÇÿ±ÿ¥Ÿä
 ŸÖŸÜŸÅŸàÿ≠ÿ© ÿßŸÑÿ¨ÿØŸäÿØÿ©
 ÿßŸÑŸÖÿπÿ∞ÿ±
ÿßŸÜ ŸÖŸàŸÑŸâ ŸÇÿ±Ÿäÿ¥
ÿ∞ŸäŸÅ
 ÿßŸÑÿ¥ÿ±ŸÅŸäÿ©
ÿ© ÿ®ŸÜ ÿÆŸÑŸäŸÅÿ© ÿßŸÑŸÉŸÑÿ®Ÿä
Ÿâ ÿßŸÑŸÉŸàŸÅŸä
Ÿâ ÿßŸÑÿ≤ÿ®ŸäÿØŸä
Ÿâ ÿßŸÑÿ≥ŸÑŸÖŸä
 ÿßŸÑÿ≤Ÿáÿ±ÿßÿ°
 ÿßŸÑŸÅŸäÿµŸÑŸäÿ©
 ÿßŸÑÿ±ŸÅŸäÿπÿ©
 ÿπŸÑŸäÿ¥ÿ©
Ÿâ ÿßŸÑŸÖÿπŸÑŸÖŸä
 ÿßŸÑŸÖŸÑŸÉ ÿπÿ®ÿØÿßŸÑÿπÿ≤Ÿäÿ≤
 ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑÿµŸÜÿßÿπŸäÿ© ÿßŸÑÿ¨ÿØŸäÿØÿ©
 ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ°
Ÿâ ÿ®ŸÜ ÿπÿØŸâ
Ÿâ ÿ®ŸÜ ÿπÿ®ÿØÿßŸÑŸÑŸá
Ÿâ ŸÖÿ§ÿ∞ŸÜ
Ÿâ ÿßŸÑÿ∑ÿ®ÿ±Ÿä
Ÿàÿ≥
Ÿä ÿ®ŸÜ ÿÆÿßŸÑÿØ ÿßŸÑÿ®ÿ±ŸÖŸÉŸä
Ÿâ ÿ®ŸÜ ÿµÿØŸäŸÇ
Ÿä ÿßŸÑÿØŸäŸÜ ÿßŸÑŸÜŸäÿ≥ÿßÿ®Ÿàÿ±Ÿä
 ÿßŸÑÿ≥ŸÑŸä
ŸÖ ÿßŸÑÿµÿØŸäŸÇŸä
ŸÜ
 ÿ´ŸÑŸäŸÖ
 ÿßŸÑŸÖŸàŸÜÿ≥Ÿäÿ©
 ÿ£ŸÖ ÿßŸÑÿ≠ŸÖÿßŸÖ ÿßŸÑÿ¥ÿ±ŸÇŸä
ÿØÿ±ÿ© ÿ®ŸÜ ÿπŸÑŸä
Ÿâ ÿ®ŸÜ ÿßŸÑŸÖŸÇÿØÿßÿØ
 ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑÿ∫ÿ±ÿ®Ÿä
Ÿâ ÿ®ŸÜ ÿ®ŸÉŸäÿ±
Ÿâ ÿßŸÑÿ∑ÿßÿ¶ŸÅŸä
Ÿâ ÿ®ŸÜ ÿπÿ®ÿØÿßŸÑÿ±ÿ≠ŸÖŸÜ
ÿ®ÿßŸÜŸä
 ŸÑŸÇÿßÿ≠
ÿßÿ° ÿßŸÑÿ®ÿ∫ÿØÿßÿØŸäÿ©
Ÿâ ÿ®ŸÜ ÿßŸÑÿ®ŸÜÿßÿ°
 ÿßŸÑŸÇŸäÿ±ŸàÿßŸÜ
Ÿàÿ© ÿ®ŸÜ ÿ¥ÿ±Ÿäÿ≠
 ÿßŸÑÿ≥ŸÑŸÖÿßŸÜŸäÿ©
ÿ≥ŸäŸá
Ÿâ ÿ®ŸÜ ÿ£ÿ®Ÿä ÿ®ŸÉÿ±
Ÿâ ÿßŸÑÿµŸÜŸáÿßÿ¨Ÿä
Ÿâ ÿßŸÑÿßŸÜÿ®ÿßÿ±Ÿä
 ŸÖŸÜŸÅŸàÿ≠ÿ©
 ÿ®ŸÜ ÿπŸÖÿ± ÿßŸÑŸÖŸÑÿ™ŸàŸÜŸä
 ÿ®ŸÜÿ®ÿßŸÜ
 ÿßŸÑŸÖŸÜÿßÿÆ
Ÿâ ÿ®ŸÜ ÿπŸÖŸäÿ±ÿ©
ÿßÿ∂ ÿ®ŸÜ ŸÇŸäÿ≥ ÿ®ŸÜ ÿßŸÑÿ£ÿπŸàÿ±
 ÿ±ŸÅŸá
 ÿßŸÑŸàÿ¥ÿßŸÖ
Ÿâ ÿßŸÑÿ≥ÿπÿØŸä
 ÿßŸÑŸÖÿ¨ÿØ
ÿ±ÿ© ÿßŸÑŸÜŸàÿ®ÿ©
ŸÖŸäÿ©
Ÿâ ŸÖÿ≠ŸÖÿØ ŸäŸâ ÿßŸÑÿ¥
ÿ±ÿ© ŸÅÿßŸÜ
Ÿâ ÿßŸÑÿ£ŸÜÿ≥Ÿä
 ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑÿµŸÜÿßÿπŸäÿ© ÿßŸÑÿ´ÿßŸÜŸäÿ©
 ÿßŸÑŸàÿ≤ÿßÿ±ÿßÿ™
Ÿâ ÿßŸÑÿ™ŸÜŸàÿÆŸä
 ÿßŸÑÿ¨ÿ±ÿØÿßÿ°
Ÿâ ÿßŸÑŸÇŸÅÿµŸä
ÿß
ŸÅÿß
 ÿßŸÑÿ™ŸÇŸàŸâ
 ÿßŸÑÿ±ÿ®Ÿäÿπ ÿßŸÑÿ¥ÿ±ŸÇŸä Ÿ¢
 ÿßŸÑÿ¨ÿ±ÿßÿØŸäÿ©
Ÿâ ÿßŸÑÿ∫ŸÖÿßÿ±Ÿä
 ÿÆÿ¥ŸÖ ÿßŸÑÿπÿßŸÜ
Ÿä ÿ®ŸÜ ÿßŸÑŸÖÿ®ÿßÿ±ŸÉ
Ÿâ ÿßŸÑÿßŸÜÿ∑ÿßŸÉŸä
ŸÖÿ©
ŸàŸäŸá
 ŸÖÿ≠ŸÖÿØ ÿ≥ÿ≠ÿßÿ±Ÿä
 ŸÇÿ±ÿ∑ÿ®ÿ©
 ÿßŸÖ ÿßŸÑÿ¥ÿπÿßŸÑ
ŸÖ ÿßŸÑÿÆÿ≤ÿ±ÿ¨Ÿä
Ÿâ ÿßŸÑÿ®ÿ±ŸÖŸÉŸä
Ÿâ ÿßŸÖÿßŸÜ
 ÿßŸÑÿ≥ÿØŸàÿ≥Ÿä
Ÿâ ÿ®ŸÜ ÿ∫ŸäŸáÿ®
ŸÖÿØ
Ÿâ ÿ®ŸÜ ÿÆŸÑÿØŸàŸÜ
 ÿßŸÑŸÖÿπÿ∞ÿ±
 ÿßÿ®Ÿà ÿÆÿ∂Ÿäÿ±
Ÿâ - ÿßŸÑÿ¨ÿ®ŸäŸÑÿ©
 ÿßŸÑŸáÿØÿß
ÿßŸá
Ÿâ ÿßŸÑÿ¥ÿßÿ∞ŸÑŸä
ŸÅÿßÿ™
 ÿßŸÑÿ®ÿ±Ÿäÿ©
ŸÖ ÿ®ŸÜ ÿßŸÑŸÅÿ±ÿ≥
Ÿä ÿ®ŸÜ ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ∫ÿ±ŸÜÿßÿ∑Ÿä
ŸÖŸäÿßÿ™
Ÿâ ÿßŸÑÿ¨ŸÅÿµŸä
ŸÖ ÿ®ŸÜ ÿπÿ≥ÿßŸÉÿ±
Ÿâ ÿßŸÑÿ≥ÿØŸäÿØ
Ÿâ ÿßŸÑŸàÿ±ÿßŸÇ
ŸÑ
ÿßÿ°
ÿ≥Ÿäÿ©
 ÿßŸÑÿπŸÖŸÑ
Ÿâ ÿ®ŸÜ ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ∫ÿ±ŸÜÿßÿ∑Ÿä
Ÿâ ÿ®ŸÜ ÿ•ÿ≥ŸÖÿßÿπŸäŸÑ
ÿµŸÜ
Ÿâ ÿ®ŸÜ ŸÇÿßÿ≥ŸÖ
 ÿ∫ÿ®Ÿäÿ±ÿ©
 ÿßÿ≥ŸÉÿßŸÜ Ÿàÿ≤ÿßÿ±ÿ© ÿßŸÑÿØÿßÿÆŸÑŸäÿ©
 ÿ£ÿ®Ÿä ÿÆÿ∂Ÿäÿ±
ŸÖ ÿßŸÑŸÉŸÜÿßŸÜŸä
Ÿâ ÿßŸÑÿ∫ÿ±ŸÜÿßÿ∑Ÿä
 ÿ£ÿ≠ŸÖÿØ ÿßŸÑÿ≥ŸÅ
 ÿßŸÑŸÖÿ±ŸÇÿ®
 ÿßŸÑÿπŸàÿØ
Ÿâ ÿ®ŸÜ ÿßÿ®ÿ±ÿßŸáŸäŸÖ ÿßŸÑÿ∑ÿßŸÑÿ®Ÿä
Ÿâ ÿßŸÑÿ±ÿßÿ≤Ÿä
ŸÅ ÿßŸÑÿπŸÜÿ®ÿ±Ÿä
 ÿßŸÑŸÖÿπŸäÿ≤ŸÑÿ©
 ÿßŸÖ ÿ≥ŸÑŸäŸÖ
Ÿâ ÿßŸÑŸàÿßÿ≥ÿ∑Ÿä
ÿ±Ÿä
ÿØÿ±Ÿá ÿßŸÑÿ™ŸàŸÜÿ≥Ÿä
Ÿâ ÿßŸÑŸÅÿ±ÿ∂Ÿä
ÿßÿµ

In [28]:
def process_neighbourhood(value):
    value = value.strip()
    if len(value) < 2:
        return None
    segments = value.split()
    segments = [segment for segment in segments if len(segment) >= 3]
    if len(segments) == 0:
        return None
    return ' '.join(segments)

In [29]:
df['neighbourhood'] = df['neighbourhood'].apply(process_neighbourhood)
df = df.dropna(subset=['neighbourhood'])

neighbourhood_counts_df = df['neighbourhood'].value_counts().reset_index()
neighbourhood_counts_df.columns = ['Neighbourhood', 'Count']

neighbourhood_counts_df

    Neighbourhood  Count
0            ÿ∑ŸàŸäŸÇ   5105
1          ÿßŸÑÿ±ŸÖÿßŸÑ   2956
2          ÿßŸÑŸÜÿ±ÿ¨ÿ≥   2092
3            ÿπŸÉÿßÿ∏   2036
4             ÿ®ÿØÿ±   1865
..            ...    ...
254          ŸÖŸäÿßÿ™      1
255           ÿ≥Ÿäÿ©      1
256         ÿßŸÑÿπŸÖŸÑ      1
257        ŸÖŸÜŸÅŸàÿ≠ÿ©      1
258        ÿßŸÑÿ™ŸÇŸàŸâ      1

[259 rows x 2 columns]

In [30]:
for neighbourhood in list(neighbourhood_counts_df['Neighbourhood']):
    print(neighbourhood)

ÿ∑ŸàŸäŸÇ
ÿßŸÑÿ±ŸÖÿßŸÑ
ÿßŸÑŸÜÿ±ÿ¨ÿ≥
ÿπŸÉÿßÿ∏
ÿ®ÿØÿ±
ÿßŸÑÿπÿßÿ±ÿ∂
ÿßŸÑŸÖŸàŸÜÿ≥Ÿäÿ©
ÿßŸÑŸÖŸÑŸÇÿß
ÿßŸÑŸÖŸáÿØŸäÿ©
ÿßŸÑÿ≠ÿ≤ŸÖ
ÿßŸÑŸäÿßÿ≥ŸÖŸäŸÜ
ÿßŸÑŸÜŸáÿ∂ÿ©
ÿ∏Ÿáÿ±ÿ© ŸÑÿ®ŸÜ
ÿßŸÑÿØÿßÿ± ÿßŸÑÿ®Ÿäÿ∂ÿßÿ°
ÿ∑Ÿäÿ®ÿ©
ÿßŸÑŸÇÿßÿØÿ≥Ÿäÿ©
ÿßŸÑÿπÿ≤Ÿäÿ≤Ÿäÿ©
ÿßŸÑÿÆŸÑŸäÿ¨
ÿßÿ¥ÿ®ŸäŸÑŸäÿ©
ŸÇÿ±ÿ∑ÿ®ÿ©
ÿßŸÑŸäÿ±ŸÖŸàŸÉ
ŸÖÿ∑ÿßÿ± ÿßŸÑŸÖŸÑŸÉ ÿÆÿßŸÑÿØ ÿßŸÑÿØŸàŸÑŸä
ÿßŸÑÿ¨ŸÜÿßÿØÿ±Ÿäÿ©
ÿßŸÑÿ≥ŸàŸäÿØŸä
ÿßŸÑÿ¥ŸÅÿß
ÿØŸäÿ±ÿßÿ®
ÿ≠ÿ∑ŸäŸÜ
ÿßŸÑŸÜÿÆŸäŸÑ
ÿ∏Ÿáÿ±ÿ© ŸÜŸÖÿßÿ±
ÿßŸÑÿ≥ÿπÿßÿØÿ©
ÿßŸÑŸÇŸäÿ±ŸàÿßŸÜ
ÿßŸÑÿµÿ≠ÿßŸÅÿ©
ŸÜŸÖÿßÿ±
ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑÿ∫ÿ±ÿ®Ÿäÿ©
ÿ∏Ÿáÿ±ÿ© ÿßŸÑÿ®ÿØŸäÿπÿ©
ÿßŸÑŸÜÿØŸâ
ÿßŸÑÿ®ŸäÿßŸÜ
ÿßŸÑÿπŸÇŸäŸÇ
ÿßŸÑÿ≠ŸÖÿ±ÿßÿ°
ÿßŸÑŸàÿßÿØŸä
ÿßŸÑÿ±Ÿàÿ∂ÿ©
ÿßŸÑÿπŸÑŸäÿß
ÿßŸÑÿ≤Ÿáÿ±ÿ©
ÿßŸÑŸÖŸÑŸÉ ŸÅŸáÿØ
ÿßŸÑŸÖÿ≠ŸÖÿØŸäÿ©
ÿßŸÑŸÖÿπŸäÿ≤ŸäŸÑÿ©
ÿßŸÑŸÜÿØŸàÿ©
ÿßŸÑÿ¥ÿ±ŸÇ
ÿßŸÑŸÜÿ≥ŸäŸÖ ÿßŸÑÿ∫ÿ±ÿ®Ÿä
ÿßŸÑÿ±ÿ®Ÿäÿπ
ÿßŸÑŸÇÿØÿ≥
ÿπÿ±ŸÇÿ©
ÿßŸÑÿßŸÜÿØŸÑÿ≥
ÿßŸÑŸÖÿµŸäŸÅ
ÿßŸÑŸÖŸÑÿ≤
ÿßŸÑÿ∫ÿØŸäÿ±
ÿßŸÑŸÖÿ±Ÿàÿ¨
ÿ≥ŸÑÿ∑ÿßŸÜÿ©
ÿßŸÑÿ≥ŸÑŸäŸÖÿßŸÜŸäÿ©
ÿ£ÿ≠ÿØ
ÿ∫ÿ±ŸÜÿßÿ∑ÿ©
ÿßŸÑŸÜŸÅŸÑ
ÿ¥ÿ®ÿ±ÿß
ÿßŸÑŸàÿ±ŸàÿØ
ÿßŸÑÿ±Ÿàÿßÿ®Ÿä
ÿßŸÑÿ±ÿ®Ÿàÿ©
ÿßŸÑŸÜÿ≤Ÿáÿ©
ÿßŸÑÿ±ŸäÿßŸÜ
ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑŸàÿ≥ÿ∑Ÿâ
ÿßÿ≠ÿØ
ÿßŸÑŸÜÿ∏ŸäŸÖ
ÿßŸÑÿ™ÿπÿßŸàŸÜ
ÿßŸÑŸÜÿ≥ŸäŸÖ ÿßŸÑÿ¥ÿ±ŸÇŸä
ÿßŸÑÿ±ÿ≠ŸÖÿßŸÜŸäÿ©
ÿßŸÑŸÅŸÑÿßÿ≠
ÿßŸÑŸÅŸäÿ≠ÿßÿ°
ÿßŸÑŸÖÿ±ÿ≥ŸÑÿßÿ™
ÿßŸÑŸÖŸÑŸÉ ŸÅŸäÿµŸÑ
ÿßŸÑÿØÿ±ŸäŸáŸÖŸäÿ©
ÿßŸÑÿßÿ≤ÿØŸáÿßÿ±
ŸÇÿßÿ∂Ÿä
ÿßŸÑŸÖÿ±Ÿàÿ©
ÿßŸÑŸÅÿßÿ±ŸàŸÇ
ÿßŸÑÿπÿµÿßŸÖŸä
ÿßŸÑŸÖŸÜÿßÿ±
ÿßŸÑÿ¨ÿ≤Ÿäÿ±ÿ©
ÿßŸÑÿ≥ŸÑÿßŸÖ
ÿßŸÑÿ®ÿØŸäÿπÿ©
ÿßŸÑŸàÿßÿ≠ÿ©
ÿßŸÑÿ¥ŸáÿØÿßÿ°
ÿßŸÑÿ≥ŸàŸäÿØŸä ÿßŸÑÿ∫ÿ±ÿ®Ÿä
ÿßŸÑÿØŸäŸÜ ÿßŸÑÿ®ÿ∫ŸàŸä
ÿßŸÑŸÖÿ∫ÿ±ÿ≤ÿßÿ™
ÿßŸÑŸÖŸÑŸÉ ÿπÿ®ÿØÿßŸÑŸÑŸá
Ÿáÿ¨ÿ±ÿ© ŸÑÿ®ŸÜ
ÿßŸÑŸÅÿßÿÆÿ±Ÿäÿ©
ÿßŸÑÿ≠ÿ±ŸäŸÖŸä
ÿßŸÑŸÖŸÜÿµŸàÿ±ÿ©
ÿßŸÑŸäŸÖÿßŸÖÿ©
ÿßŸÑÿπŸàÿßŸÑŸä
ÿµŸÑÿßÿ≠ ÿßŸÑÿØŸäŸÜ
ÿßŸÑÿÆÿßŸÑÿØŸäÿ©
ÿ±ÿßÿ™
ÿßŸÑÿßŸÜÿ≥Ÿä
ÿßŸÑŸÇÿßÿ®ŸÑÿ©
ÿπÿ®ÿØÿßŸÑŸÑŸá
ÿ¨ÿ±Ÿäÿ±
ÿßŸÑÿÆŸäÿ±
ÿßŸÑÿ∫ŸÜÿßŸÖŸäÿ©
ÿπÿØŸä
ÿßŸÑÿ∞ŸÖÿßÿ±Ÿä
ÿßŸÑÿßÿ≥ŸÉÿßŸÜ
ÿßŸÑÿ∑ÿßÿ¶Ÿä
ÿßŸÑÿ≠ŸÖÿßŸÖ ÿßŸÑÿ∫ÿ±ÿ®Ÿä
ÿßŸÑÿ≠ÿßÿ¶ÿ±
ÿÆŸÑŸäŸÅŸá
ÿßŸÑŸÖŸÜÿµŸàÿ±Ÿäÿ©
ÿπÿ±Ÿäÿ∂
ÿßŸÑÿ£ÿ≤ÿØŸä
ÿßŸÑŸÖÿµÿßŸÜÿπ
ÿÆÿßŸÑÿØ ÿßŸÑÿ®ÿ±ŸÖŸÉŸä
ÿßŸÑŸÇÿ±ÿ∑ÿ®Ÿä
ÿßŸÑÿ∂ÿ®ÿßÿ∑
ÿßŸÑŸÇÿßÿ≥ŸÖ
ÿßŸÑŸÖÿπÿ∞ÿ± ÿßŸÑÿ¥ŸÖÿßŸÑŸä
ŸÑÿ®ŸÜ
ÿßŸÑÿÆÿ≤ÿßŸÖŸâ
ÿπÿ®ÿØÿßŸÑÿπÿ≤Ÿäÿ≤
ÿ¨ÿ≤ŸÑÿ©
ÿßŸÑÿ±ÿßÿ¶ÿØ
ŸÉŸÖÿßŸÑ
ÿßŸÑÿµŸÅÿß
ÿßŸÑŸÖÿ±ÿ®ÿπ
ÿßŸÑŸÖŸÅÿ™Ÿä
ÿßŸÑÿ∑ÿßŸÑÿ®Ÿä
ÿßŸÑŸÖÿπÿ∞ÿ±
ÿßŸÑŸÖÿ∫ÿ±ÿ®Ÿä
ŸÖÿπÿßŸàŸäŸá
ÿßŸÑŸÉÿ™ÿßŸÜŸä
ÿßŸÑÿ™ŸäŸÖŸä
ÿßŸÉÿ´ŸÖ
ÿπÿ®ŸäÿØ
ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ®
ŸÖŸàŸÑŸâ ŸÇÿ±Ÿäÿ¥
ŸÖŸÜŸÅŸàÿ≠ÿ© ÿßŸÑÿ¨ÿØŸäÿØÿ©
ÿßŸÑŸÉŸàŸÅŸä
ÿßŸÑÿ≤Ÿáÿ±ÿßÿ°
ÿßŸÜŸä
ŸÇÿ≤ÿπÿ© ÿßŸÑŸÇÿ±ÿ¥Ÿä
ŸÖÿ≥ÿπŸàÿØ
ÿßŸÑÿ¥ÿ±ŸÅŸäÿ©
ÿßŸÑÿ±ŸÅŸäÿπÿ©
ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ°
ÿßŸÑÿ≤ÿ®ŸäÿØŸä
ÿßŸÑÿ∑ÿ®ÿ±Ÿä
ÿπŸÇÿ±ÿ®ÿßÿ°
ÿÆŸÑŸäŸÅÿ© ÿßŸÑŸÉŸÑÿ®Ÿä
ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑÿµŸÜÿßÿπŸäÿ© ÿßŸÑÿ¨ÿØŸäÿØÿ©
ÿπÿ™ŸäŸÇÿ©
ÿπŸÑŸäÿ¥ÿ©
ÿßŸÑŸÖÿØŸÜŸä
ÿßŸÑŸÅŸäÿµŸÑŸäÿ©
ÿßŸÑŸÖŸÑŸÉ ÿπÿ®ÿØÿßŸÑÿπÿ≤Ÿäÿ≤
ÿπÿØŸâ
ÿßŸÑÿ≥ŸÑŸÖŸä
ŸÖÿ§ÿ∞ŸÜ
ÿ∞ŸäŸÅ
ÿßŸÑŸÖÿπŸÑŸÖŸä
ÿ®ÿßŸÜŸä
ÿ¥ÿ±Ÿäÿ≠
ÿßŸÑÿπÿ±Ÿäÿ¨ÿßÿ° ÿßŸÑÿ∫ÿ±ÿ®Ÿä
ÿ®ŸÉŸäÿ±
ÿßŸÑÿ≠ŸÖÿßŸÖ ÿßŸÑÿ¥ÿ±ŸÇŸä
ÿµÿØŸäŸÇ
ÿ´ŸÑŸäŸÖ
ŸÑŸÇÿßÿ≠
ÿπÿ®ÿØÿßŸÑÿ±ÿ≠ŸÖŸÜ
ÿßŸÑÿØŸäŸÜ ÿßŸÑŸÜŸäÿ≥ÿßÿ®Ÿàÿ±Ÿä
ÿßŸÑÿ∑ÿßÿ¶ŸÅŸä
ÿßŸÑÿ®ÿ∫ÿØÿßÿØŸäÿ©
ÿßŸÑÿµÿØŸäŸÇŸä
ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ∫ÿ±ŸÜÿßÿ∑Ÿä
ÿßŸÑŸÖŸÇÿØÿßÿØ
ÿ£ÿ®Ÿä ÿ®ŸÉÿ±
ÿØÿ±ÿ© ÿπŸÑŸä
ÿßŸÑÿ≥ŸÑŸÖÿßŸÜŸäÿ©
ÿßŸÑÿµŸÜŸáÿßÿ¨Ÿä
ÿßŸÑÿ≥ŸÑŸä
ÿßŸÑÿ®ŸÜÿßÿ°
ÿßŸÑÿßŸÜÿ®ÿßÿ±Ÿä
ÿ≥ŸäŸá
ÿßŸÑÿßŸÜÿ∑ÿßŸÉŸä
ŸÅÿßŸÜ
ÿßŸÑÿ®ÿ±ŸÖŸÉŸä
ÿßŸÑÿÆÿ≤ÿ±ÿ¨Ÿä
ÿßŸÑÿ£ŸÜÿ≥Ÿä
ÿßŸÑÿ¥ÿπÿßŸÑ
ÿÆŸÑÿØŸàŸÜ
ÿßŸÑŸÖÿØŸäŸÜÿ© ÿßŸÑÿµŸÜÿßÿπŸäÿ© ÿßŸÑÿ´ÿßŸÜŸäÿ©
ÿßŸÑŸÇŸÅÿµŸä
ÿßŸÖÿßŸÜ
ŸÖÿ≠ŸÖÿØ ÿ≥ÿ≠ÿßÿ±Ÿä
ŸàŸäŸá
ÿ£ÿ®Ÿä ÿÆÿ∂Ÿäÿ±
ŸÖÿ≠ŸÖÿØ ÿßŸÑÿ¥
ÿπŸÖŸäÿ±ÿ©
ÿßŸÑŸÖÿ®ÿßÿ±ŸÉ
ÿßŸÑŸÜŸàÿ®ÿ©
ÿßŸÑÿ≥ÿØŸàÿ≥Ÿä
ŸÇŸäÿ≥ ÿßŸÑÿ£ÿπŸàÿ±
ÿßŸÑÿ™ŸÜŸàÿÆŸä
ÿßŸÑŸÖÿ¨ÿØ
ÿßŸÑÿ¨ÿ±ÿØÿßÿ°
ÿßŸÑÿ∫ŸÖÿßÿ±Ÿä
ÿßŸÑÿ¨ÿ±ÿßÿØŸäÿ©
ÿßŸÑŸàÿ≤ÿßÿ±ÿßÿ™
ÿ®ŸÜÿ®ÿßŸÜ
ÿ±ŸÅŸá
ÿßŸÑŸÖŸÜÿßÿÆ
ÿßŸÑÿ±ÿ®Ÿäÿπ ÿßŸÑÿ¥ÿ±ŸÇŸä
ÿ∫ŸäŸáÿ®
ÿßÿ≥ŸÉÿßŸÜ Ÿàÿ≤ÿßÿ±ÿ© ÿßŸÑÿØÿßÿÆŸÑŸäÿ©
ÿßŸÑÿ∫ÿ±ŸÜÿßÿ∑Ÿä
ÿßŸÑŸàÿßÿ≥ÿ∑Ÿä
ÿßŸÑŸàÿ¥ÿßŸÖ
ÿπŸÖÿ± ÿßŸÑŸÖŸÑÿ™ŸàŸÜŸä
ÿÆÿ¥ŸÖ ÿßŸÑÿπÿßŸÜ
ÿßŸÑÿ≥ÿπÿØŸä
ŸÖŸäÿ©
ÿßŸÑŸÉŸÜÿßŸÜŸä
ÿ£ÿ≠ŸÖÿØ ÿßŸÑÿ≥ŸÅ
ÿßÿ®ÿ±ÿßŸáŸäŸÖ ÿßŸÑÿ∑ÿßŸÑÿ®Ÿä
ÿßÿ®Ÿà ÿÆÿ∂Ÿäÿ±
ÿßŸÑŸáÿØÿß
ÿßŸÑŸÅÿ±ÿ≥
ÿ∫ÿ®Ÿäÿ±ÿ©
ÿßŸÑÿ≥ÿØŸäÿØ
ÿπÿ≥ÿßŸÉÿ±
ÿßŸÑŸÅÿ±ÿ∂Ÿä
ÿßŸÑŸÖÿ±ŸÇÿ®
ÿßŸÑÿ¨ŸÅÿµŸä
ÿßŸÑÿπŸàÿØ
ÿßŸÑŸàÿ±ÿßŸÇ
ÿßŸÑÿ±ÿßÿ≤Ÿä
ÿßŸÑÿπŸÜÿ®ÿ±Ÿä
ÿßŸÑŸÖÿπŸäÿ≤ŸÑÿ©
ÿ≥ŸÑŸäŸÖ
ÿØÿ±Ÿá ÿßŸÑÿ™ŸàŸÜÿ≥Ÿä
ŸÇÿßÿ≥ŸÖ
ÿ•ÿ≥ŸÖÿßÿπŸäŸÑ
ÿßŸÑÿ¨ÿ®ŸäŸÑÿ©
ÿßŸÑÿ¥ÿßÿ∞ŸÑŸä
ŸÅÿßÿ™
ÿßŸÑÿ®ÿ±Ÿäÿ©
ŸÖŸäÿßÿ™
ÿ≥Ÿäÿ©
ÿßŸÑÿπŸÖŸÑ
ŸÖŸÜŸÅŸàÿ≠ÿ©
ÿßŸÑÿ™ŸÇŸàŸâ

# Data Visualization

In [31]:
# def reshape_arabic_text(column):
#     return column.apply(lambda x: get_display(arabic_reshaper.reshape(x)))

In [32]:
# df['front_reshaped'] = reshape_arabic_text(df['front'])

# plt.figure(figsize=(10, 6))
# sns.countplot(data=df, y='front_reshaped', order=df['front_reshaped'].value_counts().index, palette='viridis')
# plt.title('Distribution of Front Orientation')
# plt.xlabel('Count')
# plt.ylabel('Front Orientation')
# plt.show();

In [33]:
# plt.figure(figsize=(10, 6))
# sns.countplot(data=df, x='lounges', order=df['lounges'].value_counts().index, palette='coolwarm')
# plt.title('Distribution of Lounges')
# plt.xlabel('Number of Lounges')
# plt.ylabel('Count')
# plt.xticks(rotation=45)
# plt.show();

In [34]:
# bathroom_counts = df['bathrooms'].value_counts()
# plt.figure(figsize=(8, 8))
# plt.pie(bathroom_counts, labels=bathroom_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
# plt.title('Distribution of Bathrooms')
# plt.show();

In [35]:
# plt.figure(figsize=(12, 8))
# sns.countplot(data=df, x='apartments', order=df['apartments'].value_counts().index, color='skyblue')
# plt.title('Distribution of Apartments (Categorical)')
# plt.xlabel('Number of Apartments')
# plt.ylabel('Count')
# plt.xticks(rotation=90)
# plt.show();

In [36]:
# df['location_reshaped'] = reshape_arabic_text(df['location'])

# plt.figure(figsize=(10, 6))
# sns.countplot(data=df, y='location_reshaped', order=df['location_reshaped'].value_counts().index, palette='magma')
# plt.title('Distribution of Location')
# plt.xlabel('Count')
# plt.ylabel('Location')
# plt.show();

In [37]:
# plt.figure(figsize=(10, 6))
# sns.countplot(data=df, x='rooms', palette='viridis')
# plt.title('Distribution of Number of Rooms')
# plt.xlabel('Number of Rooms')
# plt.ylabel('Count')
# plt.xticks(rotation=0)
# plt.show();

In [38]:
# plt.figure(figsize=(10, 6))
# sns.histplot(df['space'], bins=30, kde=True, color='skyblue')
# plt.title('Distribution of Space (Square Meters)')
# plt.xlabel('Space (Square Meters)')
# plt.ylabel('Count')
# plt.show();

In [39]:
# bool_columns = ['stairs', 'driverRoom', 'tent', 'patio', 'kitchen', 'outdoorRoom', 
#                 'garage', 'duplex', 'maidRoom', 'elevator', 'furnihsed', 'pool', 'basement']

# plt.figure(figsize=(14, 18))

# for i, col in enumerate(bool_columns, 1):
#     plt.subplot(4, 4, i)
#     sns.countplot(data=df, x=col, palette='viridis')
#     plt.title(f'Distribution of {col.capitalize()}')
#     plt.xlabel('Presence')
#     plt.ylabel('Count')
#     plt.xticks([0, 1], ['No', 'Yes'])

# plt.tight_layout()
# plt.show();

In [40]:
# plt.figure(figsize=(14, 12))

# # 1. Histogram for Street Width
# plt.subplot(2, 2, 1)
# sns.histplot(df['streetWidth'], bins=20, kde=True, color='skyblue')
# plt.title('Distribution of Street Width')
# plt.xlabel('Street Width (meters)')
# plt.ylabel('Count')

# # 2. Histogram for Price
# plt.subplot(2, 2, 2)
# sns.histplot(df['price'], bins=20, kde=True, color='coral')
# plt.title('Distribution of Price')
# plt.xlabel('Price')
# plt.ylabel('Count')

# # 3. Histogram for Square Price
# plt.subplot(2, 2, 3)
# sns.histplot(df['square price'], bins=20, kde=True, color='lightgreen')
# plt.title('Distribution of Square Price')
# plt.xlabel('Square Price')
# plt.ylabel('Count')

# # 4. Histogram for Property Age
# plt.subplot(2, 2, 4)
# sns.histplot(df['propertyAge'], bins=20, kde=True, color='lightpink')
# plt.title('Distribution of Property Age')
# plt.xlabel('Property Age (years)')
# plt.ylabel('Count')

# plt.tight_layout()
# plt.show();

# Change the Data Types

In [41]:
bool_columns = [
    'stairs', 
    'driverRoom', 
    'patio', 
    'tent', 
    'kitchen', 
    'outdoorRoom', 
    'garage', 
    'duplex', 
    'maidRoom', 
    'elevator', 
    'furnihsed', 
    'pool', 
    'basement'
]

df[bool_columns] = df[bool_columns].astype('int64')

print(df[bool_columns].dtypes)

stairs         int64
driverRoom     int64
patio          int64
tent           int64
kitchen        int64
outdoorRoom    int64
garage         int64
duplex         int64
maidRoom       int64
elevator       int64
furnihsed      int64
pool           int64
basement       int64
dtype: object

In [42]:
df['propertyAge'] = df['propertyAge'].astype('int64')

print(df['propertyAge'].dtype)

int64

# Rename Columns

In [43]:
new_column_names = {
    'front': 'front',
    'rooms': 'rooms',
    'lounges': 'lounges',
    'bathrooms': 'bathrooms',
    'streetWidth': 'street_width',
    'stairs': 'stairs',
    'propertyAge': 'property_age',
    'driverRoom': 'driver_room',
    'tent': 'tent',
    'patio': 'patio',
    'kitchen': 'kitchen',
    'outdoorRoom': 'outdoor_room',
    'garage': 'garage',
    'duplex': 'duplex',
    'space': 'space',
    'apartments': 'apartments',
    'maidRoom': 'maid_room',
    'elevator': 'elevator',
    'furnihsed': 'furnished',
    'pool': 'pool',
    'basement': 'basement',
    'neighbourhood': 'neighborhood',
    'location': 'location',
    'price': 'price',
    'square price': 'square_price'
}

df.rename(columns=new_column_names, inplace=True)

print(df.columns)

Index(['front', 'rooms', 'lounges', 'bathrooms', 'street_width', 'stairs',
       'property_age', 'driver_room', 'tent', 'patio', 'kitchen',
       'outdoor_room', 'garage', 'duplex', 'space', 'apartments', 'maid_room',
       'elevator', 'furnished', 'pool', 'basement', 'neighborhood', 'location',
       'price', 'square_price'],
      dtype='object')

# Export the processed dataframe

In [44]:
df.to_csv('df.csv', index=False)

# Data Analysis & Insights Finding

In [45]:
color_palette = ['#48c9b0', '#1abc9c', '#17a589', '#148f77',
                 '#117864', '#0e6251', '#45b39d', '#16a085',
                 '#138d75', '#117a65', '#0e6655', '#0b5345']

#### 1.1: ÿ•ÿ¨ŸÖÿßŸÑŸä ŸÇŸäŸÖÿ© ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ

* ŸÜŸÑÿßÿ≠ÿ∏ ÿ£ŸÜ ÿ•ÿ¨ŸÖÿßŸÑŸä ŸÇŸäŸÖÿ© ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂ ŸáŸà ÿßŸÑÿ£ÿπŸÑŸâ, ŸÖŸÖÿß Ÿäÿ¥Ÿäÿ± ÿ•ŸÑŸâ ÿ£ŸÜ Ÿáÿ∞Ÿá ÿßŸÑŸÖŸÜÿ∑ŸÇÿ© ÿ™ÿ¥ŸáÿØ ŸÖÿ®Ÿäÿπÿßÿ™ ÿπÿßŸÑŸäÿ© ŸÖŸÜ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿ∞ÿßÿ™ ÿßŸÑÿ£ÿ≥ÿπÿßÿ± ÿßŸÑŸÖÿ±ÿ™ŸÅÿπÿ©ÿå ÿ≥Ÿàÿßÿ° ŸÖŸÜ ÿ≠Ÿäÿ´ ÿßŸÑÿ≠ÿ¨ŸÖ ÿ£Ÿà ÿßŸÑŸÇŸäŸÖÿ©.
* ŸÅŸä ÿßŸÑŸÖŸÇÿßÿ®ŸÑ, ÿ•ÿ¨ŸÖÿßŸÑŸä ŸÇŸäŸÖÿ© ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä Ÿàÿ≥ÿ∑ ÿßŸÑÿ±Ÿäÿßÿ∂ ŸáŸà ÿßŸÑÿ£ŸÇŸÑ ÿ®ÿ¥ŸÉŸÑ ŸÖŸÑÿ≠Ÿàÿ∏, ÿπŸÑŸâ ÿßŸÑÿ±ÿ∫ŸÖ ŸÖŸÜ ÿßÿ≠ÿ™ŸÖÿßŸÑŸäÿ© Ÿàÿ¨ŸàÿØ ÿπÿØÿØ ŸÉÿ®Ÿäÿ± ŸÖŸÜ ÿßŸÑŸÖÿπÿßŸÖŸÑÿßÿ™ÿå ÿ•ŸÑÿß ÿ£ŸÜ ÿßŸÜÿÆŸÅÿßÿ∂ ÿßŸÑÿ£ÿ≥ÿπÿßÿ± ŸÅŸä Ÿáÿ∞Ÿá ÿßŸÑŸÖŸÜÿ∑ŸÇÿ© Ÿäÿ≥ÿßŸáŸÖ ŸÅŸä ÿ™ŸÇŸÑŸäÿµ ÿßŸÑŸÇŸäŸÖÿ© ÿßŸÑÿ•ÿ¨ŸÖÿßŸÑŸäÿ© ŸÑŸÑÿ≥ŸàŸÇ ŸÖŸÇÿßÿ±ŸÜÿ© ÿ®ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ£ÿÆÿ±Ÿâ. ŸÇÿØ ŸäŸÉŸàŸÜ ÿßŸÑÿ≥ÿ®ÿ® ŸÅŸä ÿµÿ∫ÿ± ÿ≠ÿ¨ŸÖ ŸàŸÖÿ≥ÿßÿ≠ÿ© ŸÖŸÜÿ∑ŸÇÿ© Ÿàÿ≥ÿ∑ ÿßŸÑÿ±Ÿäÿßÿ∂.

In [46]:
fig1 = px.histogram(
    df, x='location', y='price',
    color_discrete_sequence=color_palette,
    width=1000, height=600
)
fig1.update_layout(
    xaxis_title="ÿßŸÑŸÖŸàŸÇÿπ",
    yaxis_title="ŸÖÿ¨ŸÖŸàÿπ ÿßŸÑÿ≥ÿπÿ±",
    font=dict(size=18)
)
fig1.show();

#### 1.2: ŸÖÿ™Ÿàÿ≥ÿ∑ ÿ£ÿ≥ÿπÿßÿ± ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ

* ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ ŸÅŸä ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ™ÿ™ŸÖÿ™ÿπ ÿ®ÿ£ÿπŸÑŸâ ŸÖÿ™Ÿàÿ≥ÿ∑ ÿ£ÿ≥ÿπÿßÿ± ŸÑŸÑÿπŸÇÿßÿ±ÿßÿ™, ŸÖŸÖÿß Ÿäÿ¥Ÿäÿ± ÿ•ŸÑŸâ ÿ£ŸÜ Ÿáÿ∞Ÿá ÿßŸÑŸÖŸÜÿ∑ŸÇÿ© ÿ™ÿ≥ÿ™ŸÇÿ∑ÿ® ÿπŸÇÿßÿ±ÿßÿ™ ÿ∞ÿßÿ™ ÿ£ÿ≥ÿπÿßÿ± ŸÖÿ±ÿ™ŸÅÿπÿ©ÿå ÿ±ÿ®ŸÖÿß ÿ®ÿ≥ÿ®ÿ® ÿßŸÑÿ∑ŸÑÿ® ÿπŸÑŸâ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑŸÅÿßÿÆÿ±ÿ©, ŸÇÿ±ÿ® ÿßŸÑÿÆÿØŸÖÿßÿ™ ÿßŸÑÿπÿßŸÖÿ© ÿ£Ÿà ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ±ÿßŸÇŸäÿ©.
* ŸÅŸä ÿßŸÑŸÖŸÇÿßÿ®ŸÑ, ÿßŸÑÿ£ÿ≥ÿπÿßÿ± ŸÅŸä ÿ¨ŸÜŸàÿ® ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ£ŸÇŸÑ ÿ®ÿ¥ŸÉŸÑ ŸÖŸÑÿ≠Ÿàÿ∏ ŸÖŸÇÿßÿ±ŸÜÿ© ÿ®ÿ®ŸÇŸäÿ© ÿßŸÑŸÖŸàÿßŸÇÿπ (ŸÇÿØ ŸäŸÉŸàŸÜ ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂ ÿßŸÑÿ£ŸÇÿ±ÿ®), ŸÖŸÖÿß ŸÇÿØ ŸäÿπŸÜŸä ÿ£ŸÜ ÿßŸÑŸÖŸÜÿ∑ŸÇÿ© ÿ™ÿ≠ÿ™ŸàŸä ÿπŸÑŸâ ÿπŸÇÿßÿ±ÿßÿ™ ÿ£ŸÉÿ´ÿ± ŸÖŸÑÿßÿ°ŸÖÿ© ŸÖŸÜ ÿ≠Ÿäÿ´ ÿßŸÑÿ£ÿ≥ÿπÿßÿ±ÿå ŸÖŸÖÿß Ÿäÿ¨ÿπŸÑŸáÿß ÿ£ŸÉÿ´ÿ± ŸÇÿßÿ®ŸÑŸäÿ© ŸÑŸÑŸàÿµŸàŸÑ ŸÑŸÑŸÖÿ¥ÿ™ÿ±ŸäŸÜ ÿ£Ÿà ÿßŸÑŸÖÿ≥ÿ™ÿ£ÿ¨ÿ±ŸäŸÜ ÿ∞ŸàŸä ÿßŸÑÿØÿÆŸÑ ÿßŸÑŸÖÿ™Ÿàÿ≥ÿ∑.

In [47]:
avg_price_df = df.groupby('location')['price'].mean().reset_index()

fig2 = px.bar(
    avg_price_df, 
    x='location', 
    y='price',
    color_discrete_sequence=color_palette,
    width=1000, 
    height=600
)
fig2.update_layout(
    xaxis_title="ÿßŸÑŸÖŸàŸÇÿπ",
    yaxis_title="ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ±",
    font=dict(size=18)
)
fig2.show();

#### 1.3: ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ

* ŸÜŸÑÿßÿ≠ÿ∏ ÿßŸÜ ŸÖŸÜÿ∑ŸÇÿ™Ÿä ÿ¥ŸÖÿßŸÑ Ÿàÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ™ÿ≠ÿ™ŸàŸä ÿπŸÑŸâ ÿπÿØÿØ ŸÉÿ®Ÿäÿ± ŸÖŸÜ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑÿ™Ÿä Ÿäÿ™ŸÖ ÿ®ŸäÿπŸáÿß ÿ®ÿ£ÿ≥ÿπÿßÿ± ÿ£ÿπŸÑŸâÿå ŸÅŸä ÿ≠ŸäŸÜ ÿ£ŸÜ ÿ¨ŸÜŸàÿ® Ÿàÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂ ŸäŸÖŸäŸÑÿß ÿ•ŸÑŸâ ÿßŸÖÿ™ŸÑÿßŸÉ ÿπŸÇÿßÿ±ÿßÿ™ ÿ®ÿ£ÿ≥ÿπÿßÿ± ŸÖÿπŸÇŸàŸÑÿ© ŸÅŸä ÿßŸÑŸÜÿ∑ÿßŸÇ ÿßŸÑÿ≥ÿπÿ±Ÿä ÿßŸÑŸÖŸÜÿÆŸÅÿ∂.

In [48]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_no_outliers = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]

fig3 = px.histogram(
    df_no_outliers, 
    x='price',
    color='location',
    histfunc='count',
    color_discrete_sequence=color_palette, 
    width=1000, 
    height=600,
    labels={'price': 'Real Estate Prices', 'location': 'Location'}
)

fig3.update_layout(
    xaxis_title="ÿßŸÑÿ≥ÿπÿ±",
    yaxis_title="ÿπÿØÿØ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™",
    legend_title="ÿßŸÑŸÖŸàŸÇÿπ",
    font=dict(size=18),
    barmode='stack'
)

fig3.show();

#### 2: ÿßŸÑÿπŸÑÿßŸÇÿ© ÿ®ŸäŸÜ ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ŸàÿßŸÑÿ≥ÿπÿ± ÿßŸÑÿ•ÿ¨ŸÖÿßŸÑŸä ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ

* ÿ™ÿ™ŸÖŸäÿ≤ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ®ÿ≥ÿπÿ± ÿ£ÿπŸÑŸâ ÿ®ÿ¥ŸÉŸÑ ÿπÿßŸÖ ŸÑŸÑŸÖÿ™ÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ŸÖŸÇÿßÿ±ŸÜÿ© ÿ®ÿßŸÑŸÖŸàÿßŸÇÿπ ÿßŸÑÿ£ÿÆÿ±Ÿâÿå ŸÖŸÖÿß ŸäÿπŸÉÿ≥ ÿ∑ÿ®Ÿäÿπÿ™Ÿáÿß ÿßŸÑŸÖÿ™ŸÖŸäÿ≤ÿ©. ŸàŸÖÿπ ÿ∞ŸÑŸÉÿå ŸáŸÜÿßŸÉ ÿπÿØÿØ ŸÇŸÑŸäŸÑ ŸÖŸÜ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑÿ™Ÿä ÿßŸÜÿ≠ÿ±ŸÅÿ™ ÿ®ÿ¥ŸÉŸÑ ŸÉÿ®Ÿäÿ± ÿπŸÜ Ÿáÿ∞ÿß ÿßŸÑÿßÿ™ÿ¨ÿßŸáÿå ŸÖŸÖÿß Ÿäÿ¥Ÿäÿ± ÿ•ŸÖÿß ÿ•ŸÑŸâ ÿπŸÇÿßÿ±ÿßÿ™ ÿ£ŸÉÿ®ÿ± ÿ£Ÿà ÿπŸÇÿßÿ±ÿßÿ™ ŸÅÿßÿÆÿ±ÿ©.

In [49]:
fig4 = px.scatter(
    df, x='square_price', y='price', color="location",
    color_discrete_sequence=color_palette,
    width=1000, height=600
)
fig4.update_layout(
    xaxis_title="ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ",
    yaxis_title="ÿßŸÑÿ≥ÿπÿ± ÿßŸÑÿßÿ¨ŸÖÿßŸÑŸä",
    legend_title="ÿßŸÑŸÖŸàŸÇÿπ",
    font=dict(size=18)
)

fig4.show();

#### 3: ÿßŸÑÿπŸÑÿßŸÇÿ© ÿ®ŸäŸÜ ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ŸàŸÖÿ≥ÿßÿ≠ÿ© ÿßŸÑÿπŸÇÿßÿ± ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ

* ÿπÿßÿØÿ©Ÿã ŸÖÿß ÿ™ÿ™ÿ±ÿßŸàÿ≠ ŸÖÿ≥ÿßÿ≠ÿ© ŸÖÿπÿ∏ŸÖ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑÿ™ÿµŸÑ ÿ•ŸÑŸâ 2000 ŸÖÿ™ÿ± ŸÖÿ±ÿ®ÿπ ŸÉÿ≠ÿØ ÿ£ŸÇÿµŸâ.
* ÿ£ŸÖÿß ÿ®ÿßŸÑŸÜÿ≥ÿ®ÿ© ŸÑÿ≥ÿπÿ± ÿßŸÑŸÖÿ™ÿ± ÿßŸÑŸÖÿ±ÿ®ÿπÿå ŸÅŸáŸà ŸäÿµŸÑ ŸÅŸä ÿßŸÑÿ∫ÿßŸÑÿ® ÿ•ŸÑŸâ 20,000 ÿ±ŸäÿßŸÑ ÿ≥ÿπŸàÿØŸä ŸÉÿ≠ÿØ ÿ£ŸÇÿµŸâ.
* ŸÜŸÑÿßÿ≠ÿ∏ ŸÜŸÖÿ∑ ÿ∫Ÿäÿ± ÿ™ŸÇŸÑŸäÿØŸä ŸÅŸä ÿßŸÑÿπÿØŸäÿØ ŸÖŸÜ ŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂ÿå ÿ≠Ÿäÿ´ Ÿäÿ±ÿ™ŸÅÿπ ÿ≥ÿπÿ± ÿßŸÑŸÖÿ™ÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ÿ®ÿßŸÑŸÜÿ≥ÿ®ÿ© ŸÑŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿ∞ÿßÿ™ ÿßŸÑŸÖÿ≥ÿßÿ≠ÿßÿ™ ÿßŸÑÿ£ÿµÿ∫ÿ±ÿå ŸÖŸÖÿß Ÿäÿ¥Ÿäÿ± ÿ•ŸÑŸâ Ÿàÿ¨ŸàÿØ ÿπŸàÿßŸÖŸÑ ÿ£ÿÆÿ±Ÿâ ÿ™ÿ§ÿ´ÿ± ÿπŸÑŸâ ÿ≤ŸäÿßÿØÿ© ÿßŸÑÿ≥ÿπÿ± ÿ®ÿÆŸÑÿßŸÅ ÿßŸÑŸÖŸàŸÇÿπ ŸàÿßŸÑŸÖŸÜÿ∑ŸÇÿ©.

In [50]:
fig5 = px.scatter(
    df, x='square_price', y='space', color="location",
    color_discrete_sequence=color_palette,
    width=1000, height=600
)

fig5.update_layout(
    xaxis_title="ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ",
    yaxis_title="ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ©",
    legend_title="ÿßŸÑŸÖŸàŸÇÿπ",
    font=dict(size=18)
)

fig5.show();

#### 6: ÿ™ŸàŸÅÿ± ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ© ÿπÿ®ÿ± ÿßŸÑŸÖŸàÿßŸÇÿπ ŸÖŸàÿ≤ÿπÿ© ÿ≠ÿ≥ÿ® ÿ£ÿπŸÖÿßÿ± ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™

* ÿ™ÿ™ÿ±ŸÉÿ≤ ŸÖÿπÿ∏ŸÖ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑÿ™Ÿä ŸÑÿß ÿ™ÿ™ÿ¨ÿßŸàÿ≤ ÿ£ÿπŸÖÿßÿ±Ÿáÿß 10 ÿ≥ŸÜŸàÿßÿ™ ŸÅŸä ŸÖŸÜÿ∑ŸÇÿ© ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂ÿå ŸÖÿπ Ÿàÿ¨ŸàÿØ ÿ™Ÿàÿßÿ¨ÿØ ŸÖŸÑÿ≠Ÿàÿ∏ ÿ£Ÿäÿ∂Ÿãÿß ŸÅŸä ŸÖŸÜÿ∑ŸÇÿ© ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂.
* ÿ£ŸÖÿß ÿ®ŸÇŸäÿ© ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑÿ™Ÿä ÿ™ÿ™ÿ¨ÿßŸàÿ≤ ÿ£ÿπŸÖÿßÿ±Ÿáÿß 10 ÿ≥ŸÜŸàÿßÿ™ÿå ŸÅÿ•ŸÜ ÿßŸÑÿ∫ÿßŸÑÿ®Ÿäÿ© ÿßŸÑÿπÿ∏ŸÖŸâ ŸÖŸÜŸáÿß ÿ™ŸÇÿπ ŸÅŸä ŸÖŸÜÿ∑ŸÇÿ© ÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂, Ÿàÿ®ÿ∞ŸÑŸÉ ŸÖŸÜ ÿßŸÑŸÖŸÖŸÉŸÜ ÿßÿπÿ™ÿ®ÿßÿ±Ÿáÿß ÿßŸÑŸÖŸÜÿ∑ŸÇÿ© ÿßŸÑÿ£ŸÇÿØŸÖ.
* ŸÜŸÑÿßÿ≠ÿ∏ ÿ£Ÿäÿ∂ÿß ÿßŸÜ ÿ£ÿπŸÑŸâ ŸÖÿ≥ÿßÿ≠ÿ© ŸÖÿ™ÿßÿ≠ÿ© ŸÑŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿ™ŸÇÿπ ŸÅŸä ÿ¥ŸÖÿßŸÑ Ÿàÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂, ÿ£ŸÖÿß ÿ®ÿßŸÑŸÜÿ≥ÿ®ÿ© ŸÑŸàÿ≥ÿ∑ ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÅŸáŸä ÿßŸÑÿ£ŸÇŸÑ ÿ™ŸàŸÅÿ±ÿß ŸÑŸÑŸÖÿ≥ÿßÿ≠ÿ©.

In [51]:
def categorize_property_age(years):
    if years <= 10:
        return 'ÿ£ŸÇŸÑ ŸÖŸÜ ÿπÿ¥ÿ± ÿ≥ŸÜŸàÿßÿ™'
    elif years <= 20:
        return 'ŸÖÿßÿ®ŸäŸÜ ÿπÿ¥ÿ± ÿßŸÑŸâ ÿπÿ¥ÿ±ŸäŸÜ ÿ≥ŸÜÿ©'
    elif years <= 30:
        return 'ŸÖÿßÿ®ŸäŸÜ ÿπÿ¥ÿ±ŸäŸÜ ÿßŸÑŸâ ÿ´ŸÑÿßÿ´ŸäŸÜ ÿ≥ŸÜÿ©'
    else:
        return 'ÿ£ŸÉÿ®ÿ± ŸÖŸÜ ÿ´ŸÑÿßÿ´ŸäŸÜ ÿ≥ŸÜÿ©'

df['property_age_category'] = df['property_age'].apply(categorize_property_age)

In [52]:
fig6 = px.histogram(
    df, x='location', y='space', color='property_age_category',
    category_orders={'property_age_category': [
        'ÿ£ŸÇŸÑ ŸÖŸÜ ÿπÿ¥ÿ± ÿ≥ŸÜŸàÿßÿ™',
        'ŸÖÿßÿ®ŸäŸÜ ÿπÿ¥ÿ± ÿßŸÑŸâ ÿπÿ¥ÿ±ŸäŸÜ ÿ≥ŸÜÿ©',
        'ŸÖÿßÿ®ŸäŸÜ ÿπÿ¥ÿ±ŸäŸÜ ÿßŸÑŸâ ÿ´ŸÑÿßÿ´ŸäŸÜ ÿ≥ŸÜÿ©',
        'ÿ£ŸÉÿ®ÿ± ŸÖŸÜ ÿ´ŸÑÿßÿ´ŸäŸÜ ÿ≥ŸÜÿ©'
    ]},
    color_discrete_sequence=color_palette, template="plotly_white"
)
fig6.update_layout(
    xaxis_title='ÿßŸÑŸÖŸàŸÇÿπ',
    yaxis_title='ŸÖÿ¨ŸÖŸàÿπ ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ© (ŸÖÿ™ÿ± ŸÖÿ±ÿ®ÿπ)',
    legend_title="ÿπŸÖÿ± ÿßŸÑÿπŸÇÿßÿ±",
    font=dict(size=18)
)
fig6.show();

#### 7: ÿ£ÿπŸÑŸâ 3 ÿ£ÿ≠Ÿäÿßÿ° ÿ£ÿ≥ÿπÿßÿ± ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©

In [53]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_no_outliers = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]

average_prices = df_no_outliers.groupby(['location', 'neighborhood'])['price'].mean().reset_index()
average_prices = average_prices.sort_values(['location', 'price'], ascending=[True, False])
top_neighborhoods = average_prices.groupby('location').head(3)
low_neighborhoods = average_prices.groupby('location').tail(3)

In [54]:
fig7 = px.bar(
    top_neighborhoods, 
    x='neighborhood', 
    y='price', 
    color='location',
    color_discrete_sequence=color_palette, 
    template="plotly_white",
    labels={'price': 'Average Price', 'neighborhood': 'Neighborhood'}
)
fig7.update_layout(
    xaxis_title="ÿßŸÑÿ≠Ÿä",
    yaxis_title="ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ±",
    font=dict(size=16)
)
fig7.show();

#### 8: ÿ£ŸÇŸÑ 3 ÿ£ÿ≠Ÿäÿßÿ° ÿ£ÿ≥ÿπÿßÿ± ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©

In [55]:
fig8 = px.bar(
    low_neighborhoods, 
    x='neighborhood', 
    y='price', 
    color='location',
    color_discrete_sequence=color_palette, 
    template="plotly_white",
    labels={'price': 'Average Price', 'neighborhood': 'Neighborhood'}
)
fig8.update_layout(
    xaxis_title="ÿßŸÑÿ≠Ÿä",
    yaxis_title="ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ±",
    font=dict(size=16)
)
fig8.show();

#### 9: ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑŸÖÿ≥ÿßÿ®ÿ≠ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©

In [56]:
df['pool'] = df['pool'].map({0: 'ŸÑÿß', 1: 'ŸÜÿπŸÖ'})

fig9 = px.histogram(
    df, 
    x='location', 
    y='space', 
    color='pool',
    histfunc='count',
    color_discrete_sequence=color_palette, 
    template="plotly_white",
    labels={
        'location': 'ÿßŸÑŸÖŸàŸÇÿπ',
        'space': 'ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ©',
        'pool': 'Ÿàÿ¨ŸàÿØ ŸÖÿ≥ÿ®ÿ≠'
    }
)

fig9.update_layout(
    xaxis_title="ÿßŸÑŸÖŸàŸÇÿπ",
    yaxis_title="ÿπÿØÿØ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™",
    font=dict(size=18)
)

fig9.show();

#### 10: ŸÖÿ™Ÿàÿ≥ÿ∑ ŸÖÿ≥ÿßÿ≠ÿ© ÿßŸÑÿπŸÇÿßÿ± (ÿ£ŸÅÿ∂ŸÑ 10 ÿ£ÿ≠Ÿäÿßÿ° ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂)

In [57]:
average_sizes_by_neighborhood = df.groupby('neighborhood')['space'].mean().reset_index()
top_neighborhoods = average_sizes_by_neighborhood.nlargest(10, 'space')

fig10 = px.bar(
    top_neighborhoods, x='neighborhood', y='space',
    labels={'neighborhood': 'Neighborhood', 'space': 'Average House Size'},
    color_discrete_sequence=color_palette, template="plotly_white"
)
fig10.show();

#### 11: ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ± ÿ≠ÿ≥ÿ® ÿπŸÖÿ± ÿßŸÑÿπŸÇÿßÿ±

In [58]:
selected_locations = df['location'].value_counts().index.tolist()
filtered_df = df[df['location'].isin(selected_locations)]

average_price_by_age_and_location = (
    filtered_df.groupby(['property_age', 'location'])['price']
    .mean()
    .reset_index()
)

fig11 = px.line(
    average_price_by_age_and_location, 
    x='property_age', 
    y='price', 
    color='location',
    labels={
        'property_age': 'ÿπŸÖÿ± ÿßŸÑÿπŸÇÿßÿ±',
        'price': 'ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ±',
        'location': 'ÿßŸÑŸÖŸÜÿ∑ŸÇÿ©'
    },
    color_discrete_sequence=color_palette, 
    template="plotly_white"
)

fig11.update_layout(
    xaxis_title="ÿπŸÖÿ± ÿßŸÑÿπŸÇÿßÿ±",
    yaxis_title="ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ±",
    font=dict(size=18)
)

fig11.show();

#### 12: ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿ≠ÿ≥ÿ® ŸÜŸàÿπ ÿßŸÑŸàÿßÿ¨Ÿáÿ©

In [59]:
front_counts = df['front'].value_counts()
avg_prices = df.groupby('front')['price'].mean()

pie_data = pd.DataFrame({
    'Front': front_counts.index,
    'Count': front_counts.values,
    'Average Price': avg_prices.loc[front_counts.index].values
})

fig12 = px.pie(
    pie_data,
    values='Count',
    names='Front',
    hover_data={'Average Price': ':$.2f'},
    color_discrete_sequence=color_palette
)

percentages = pie_data['Count'] / pie_data['Count'].sum() * 100

def format_text(values, percentages, threshold=5):
    return [
        f"{pct:.1f}%" if pct >= threshold else ""
        for label, pct in zip(values, percentages)
    ]

fig12.update_traces(
    text=format_text(pie_data['Front'], percentages),
    textinfo='text',
    hoverinfo='label+value+percent',
)

fig12.update_layout(
    font=dict(size=18)
)

fig12.show();

#### 13. ÿ™ÿ≥ŸÑÿ≥ŸÑ ÿßŸÑŸÖŸàÿßŸÇÿπ ŸàÿßŸÑÿ£ÿ≠Ÿäÿßÿ° ÿßŸÑÿ™Ÿä ÿ™ÿ≠ÿ™ŸàŸä ÿπŸÑŸâ ÿ£ŸÉÿ´ÿ± ŸÖŸÜ 100 ÿπŸÇÿßÿ±

In [60]:
df2 = df[df['neighborhood'].map(df['neighborhood'].value_counts()) > 100]

fig13 = px.sunburst(
    df2, path=['location', 'neighborhood'],
    color_discrete_sequence=color_palette
)

fig13.update_layout(
    font=dict(size=18)
)

fig13.show();

In [61]:
fig13.update_layout(
    font=dict(color="white", size=18),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(0, 0, 0, 0)'
)

fig13.update_traces(
    textfont=dict(color="white")
)

#### 14: ÿπÿ±ÿ∂ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ŸÅŸä ÿ¨ŸÖŸäÿπ ŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂

* Ÿäÿ™ÿ±ÿßŸàÿ≠ ÿπÿ±ÿ∂ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ŸÅŸä ÿ¨ŸÖŸäÿπ ŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ®ŸäŸÜ 15 Ÿà 25 ŸÖÿ™ÿ±Ÿãÿß.
* ŸÅŸä ÿßŸÑÿ£ÿ¨ÿ≤ÿßÿ° ÿßŸÑÿ¨ŸÜŸàÿ®Ÿäÿ© ŸàÿßŸÑÿ∫ÿ±ÿ®Ÿäÿ© ŸÖŸÜ ÿßŸÑÿ±Ÿäÿßÿ∂ÿå ŸáŸÜÿßŸÉ ÿßŸÑŸÖÿ≤ŸäÿØ ŸÖŸÜ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ÿ∞ÿßÿ™ ÿßŸÑÿπÿ±ÿ∂ ÿßŸÑÿ£ŸÉÿ®ÿ± ŸÖŸÇÿßÿ±ŸÜÿ© ÿ®ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ¥ÿ±ŸÇŸäÿ© ŸàÿßŸÑÿ¥ŸÖÿßŸÑŸäÿ© ŸÖŸÜ ÿßŸÑÿ±Ÿäÿßÿ∂.

In [62]:
fig14 = make_subplots(rows=2, cols=2, subplot_titles=['ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ¨ŸÜŸàÿ® ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂'])

categories = ['ÿ¥ŸÖÿßŸÑ ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ¨ŸÜŸàÿ® ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ¥ÿ±ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂', 'ÿ∫ÿ±ÿ® ÿßŸÑÿ±Ÿäÿßÿ∂']

for i, category in enumerate(categories, 1):
    filtered_df = df[df['location'] == category]
    histogram = go.Histogram(
        x=filtered_df['street_width'],
        nbinsx=20,
        showlegend=False, 
        marker=dict(color=color_palette)

    )
    row = (i - 1) // 2 + 1
    col = (i - 1) % 2 + 1
    fig14.add_trace(histogram, row=row, col=col)

fig14.update_layout(
    xaxis=dict(title='ÿπÿ±ÿ∂ ÿßŸÑÿ¥ÿßÿ±ÿπ', gridcolor="rgba(255, 255, 255, 0.2)", gridwidth=0.5),
    yaxis=dict(title='ÿßŸÑÿ™ŸÉÿ±ÿßÿ±', gridcolor="rgba(255, 255, 255, 0.2)", gridwidth=0.5),
    plot_bgcolor='rgba(0,0,0,0)',
    paper_bgcolor="rgba(0,0,0,0)"
)

fig14.show();

#### 15: ÿ™ŸàŸÅÿ± ÿßŸÑŸÇÿ±ÿßÿ¨ÿßÿ™ ŸàÿπŸÑÿßŸÇÿ™Ÿá ÿ®ÿπÿ±ÿ∂ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ÿ∫Ÿäÿ± ÿßŸÑŸÖŸÜÿ™ÿ∏ŸÖ

* ÿ®ÿßŸÑŸÜÿ≥ÿ®ÿ© ŸÑŸÑÿ¥ÿßÿ±ÿπ ÿßŸÑÿ∂ŸäŸÇ, ŸÅŸÑŸÇÿØ ÿßŸÅÿ™ÿ±ÿ∂ŸÜÿß ÿßŸÜ ÿßŸÑÿ¥ÿßÿ±ÿπ ÿßŸÑÿ∂ŸäŸÇ ŸäŸÉŸàŸÜ ÿ£ŸÇŸÑ ŸÖŸÜ 12 ŸÖÿ™ÿ± ŸÑŸÉŸÑ ÿπŸÇÿßÿ±.
* ŸÅŸä ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ÿ∫Ÿäÿ± ÿßŸÑŸÖŸÜÿ™ÿ∏ŸÖÿ©ÿå ÿ™Ÿèÿ¨ÿ®ÿ± ÿßŸÑŸÅŸäŸÑÿßÿ™ ÿßŸÑÿ™Ÿä ŸÑÿß ÿ™ÿ≠ÿ™ŸàŸä ÿπŸÑŸâ ÿ¨ÿ±ÿßÿ¨ÿßÿ™ ÿßŸÑÿ≥ŸÉÿßŸÜ ÿπŸÑŸâ ÿ±ŸÉŸÜ ÿ≥Ÿäÿßÿ±ÿßÿ™ŸáŸÖ ŸÅŸä ÿßŸÑÿ¥Ÿàÿßÿ±ÿπÿå ŸÖŸÖÿß Ÿäÿ§ÿØŸä ÿ•ŸÑŸâ ÿ™ÿ∂ŸäŸäŸÇ ÿßŸÑÿ∑ÿ±ŸÇ.
* ŸäÿÆÿ™ÿßÿ± ŸÜÿ≥ÿ®ÿ© ŸÉÿ®Ÿäÿ±ÿ© ŸÖŸÜ ÿßŸÑŸÜÿßÿ≥ ÿ®ŸÜÿßÿ° ÿ¨ÿ±ÿßÿ¨ÿßÿ™ ŸÑÿ™ÿ¨ŸÜÿ® ŸÖÿ¥ŸÉŸÑÿ© ÿ∂ŸäŸÇ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ŸàŸÜŸÇÿµ ÿ£ŸÖÿßŸÉŸÜ ŸàŸÇŸàŸÅ ÿßŸÑÿ≥Ÿäÿßÿ±ÿßÿ™.

In [63]:
filtered_df = df[df['street_width'] < 12]
count_data = filtered_df['garage'].value_counts().reset_index()
count_data.columns = ['ÿ™ŸàÿßŸÅÿ± ÿßŸÑŸÇÿ±ÿßÿ¨', 'ÿßŸÑÿπÿØÿØ']

count_data['ÿ™ŸàÿßŸÅÿ± ÿßŸÑŸÇÿ±ÿßÿ¨'] = count_data['ÿ™ŸàÿßŸÅÿ± ÿßŸÑŸÇÿ±ÿßÿ¨'].replace({0: 'ŸÑÿß ŸäŸàÿ¨ÿØ ŸÇÿ±ÿßÿ¨', 1: 'ŸäŸàÿ¨ÿØ ŸÇÿ±ÿßÿ¨'})

color_palette = ['#48c9b0', '#1abc9c']

fig15 = px.pie(count_data, values='ÿßŸÑÿπÿØÿØ', names='ÿ™ŸàÿßŸÅÿ± ÿßŸÑŸÇÿ±ÿßÿ¨', color_discrete_sequence=color_palette, hole=0.4)

fig15.update_layout(
    plot_bgcolor='rgba(0,0,0,0)',
    paper_bgcolor="rgba(0, 0, 0, 0)",
    colorway=color_palette
)

fig15.show();

# Build the Dashboard using Plotly-Dash

In [64]:
common_layout = dict(
    xaxis=dict(gridcolor="rgba(255, 255, 255, 0.2)", gridwidth=0.5),
    yaxis=dict(gridcolor="rgba(255, 255, 255, 0.2)", gridwidth=0.5),
    plot_bgcolor='rgba(0,0,0,0)',
    paper_bgcolor="rgba(0,0,0,0)",
    font={"color": "white"}
)

In [65]:
figs = [
    fig1, fig2, fig3,
    fig6,
    fig7, fig8, fig9,
    fig10, fig12,
    fig13, fig14, fig15
]

for fig in figs:
    fig.update_layout(
        **common_layout,
        width=450, height=400
    )
    if fig.data[0]['type'] == 'pie':
        fig.update_traces(textfont=dict(color='white'))
    fig.update_layout(font={"color": "white"})

In [66]:
fig4.update_layout(
        **common_layout,
        width=900, height=400
    )

fig5.update_layout(
        **common_layout,
        width=900, height=400
    )

fig11.update_layout(
        **common_layout,
        width=900, height=400
    )

fig14.update_layout(
        **common_layout,
        width=900, height=400
    )

In [67]:
external_stylesheets = [
    "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@600&display=swap"
]

In [68]:
app = JupyterDash(__name__, external_stylesheets=external_stylesheets)

In [69]:
app.head = [
    ('''
    <style type="text/css">
    body {
        margin:0;
        padding: 0;

    }
    </style>
    ''')
]

In [70]:
app.layout = html.Div(
    style={
        'margin': '-8px 0px 0px -8px',
        'background': 'linear-gradient(45deg,#020f11, #07828e)',
        'fontFamily': 'IBM Plex Sans Arabic',
        'minHeight': '100vh',
        'width': '100%',
        'padding': '20px',
        'overflowx': 'hidden',
        'boxSizing': 'border-box'
    },
    children=[

        html.Div(
            style={
                'display': 'flex', 
                'alignItems': 'center', 
                'justifyContent': 'center', 
                'gap': '20px', 
                'marginBottom': '40px'
            },
            children=[
                html.Div(
                    style={'flex': '1', 'textAlign': 'center'},
                    children=[
                        html.H1(
                            children='ŸÑŸàÿ≠ÿ© ŸÖÿπŸÑŸàŸÖÿßÿ™ ÿ™ÿ≠ŸÑŸäŸÑÿßÿ™ ÿπŸÇÿßÿ±ÿßÿ™ ÿßŸÑÿ±Ÿäÿßÿ∂',
                            style={'margin': '0', 'color': 'white'}
                        ),
                        html.Div(
                            children='ÿ™ŸÇÿØŸÖ Ÿáÿ∞Ÿá ÿßŸÑŸÑŸàÿ≠ÿ© ŸÖÿπŸÑŸàŸÖÿßÿ™ Ÿàÿ™ÿ≠ŸÑŸäŸÑÿßÿ™ ŸÖÿ™ÿπŸÖŸÇÿ© ÿ≠ŸàŸÑ ÿ≥ŸàŸÇ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ŸÖÿØŸäŸÜÿ© ÿßŸÑÿ±Ÿäÿßÿ∂. '
                                      'ŸÜŸÇŸàŸÖ ÿ®ÿ™ÿ≠ŸÑŸäŸÑ ŸÇŸäŸÖ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ÿå ÿßŸÑÿ£ÿ≥ÿπÿßÿ± ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàÿßŸÇÿπÿå ÿßŸÑÿπŸàÿßŸÖŸÑ ÿßŸÑŸÖÿ§ÿ´ÿ±ÿ© ŸÅŸä ÿßŸÑÿ≥ŸàŸÇÿå '
                                      'ŸàÿßŸÑÿßÿ™ÿ¨ÿßŸáÿßÿ™ ÿßŸÑÿ±ÿ¶Ÿäÿ≥Ÿäÿ©ÿå ŸÑŸÖÿ≥ÿßÿπÿØÿ™ŸÉ ŸÅŸä ÿßÿ™ÿÆÿßÿ∞ ŸÇÿ±ÿßÿ±ÿßÿ™ ŸÖÿØÿ±Ÿàÿ≥ÿ© ŸÅŸä ÿßÿ≥ÿ™ÿ´ŸÖÿßÿ±ÿßÿ™ŸÉ ÿßŸÑÿπŸÇÿßÿ±Ÿäÿ©.\n\n'
                                      'ÿ≥Ÿàÿßÿ° ŸÉŸÜÿ™ ÿ™ÿ®ÿ≠ÿ´ ÿπŸÜ ŸÖÿπŸÑŸàŸÖÿßÿ™ ÿ≠ŸàŸÑ ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ™Ÿä ÿ™ÿ™ŸÖÿ™ÿπ ÿ®ÿ£ÿπŸÑŸâ ÿßŸÑÿ£ÿ≥ÿπÿßÿ± ÿ£Ÿà ÿ™ÿ™ÿ∑ŸÑÿπ ÿ•ŸÑŸâ ŸÖÿπÿ±ŸÅÿ© '
                                      'ŸÉŸäŸÅŸäÿ© ÿ™ÿ£ÿ´Ÿäÿ± ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ© ŸàÿßŸÑÿπŸÖÿ± ÿπŸÑŸâ ÿßŸÑÿ£ÿ≥ÿπÿßÿ±ÿå ŸÅÿ•ŸÜ Ÿáÿ∞Ÿá ÿßŸÑŸÑŸàÿ≠ÿ© ÿ™ŸàŸÅÿ± ŸÑŸÉ ÿ±ÿ§Ÿâ ÿØŸÇŸäŸÇÿ© Ÿàÿ¥ÿßŸÖŸÑÿ© '
                                      'ÿ≠ŸàŸÑ ÿ≥ŸàŸÇ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂.',
                            style={'color': 'white'}
                        )
                    ]
                ),
            ]
        ),

        html.Hr(
            style={
                'border': 'none', 
                'height': '2px', 
                'background': 'linear-gradient(to right, #020f11, #07828e)', 
                'margin': '20px 0'
            }
        ),

        # Group 1: General Market Overview
        html.Div(
            children=[
                html.H2(
                    children='ŸÜÿ∏ÿ±ÿ© ÿπÿßŸÖÿ© ÿπÿßŸÖÿ© ÿπŸÑŸâ ÿ≥ŸàŸÇ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂',
                    style={'color': 'white', 'textAlign': 'center', 'marginBottom': '20px'}
                ),

                html.Div(
                    style={'display': 'flex', 'flexWrap': 'wrap', 'gap': '20px', 'justifyContent': 'center', 'marginTop': '30px', 'marginBottom': '30px'},
                    children=[
                        
                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ•ÿ¨ŸÖÿßŸÑŸä ŸÇŸäŸÖÿ© ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig1)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ŸÖÿ™Ÿàÿ≥ÿ∑ ÿ£ÿ≥ÿπÿßÿ± ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig2)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸÜÿßÿ∑ŸÇ', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig3)
                                ]
                            ),
                        ]),

                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ£ÿπŸÑŸâ ÿ´ŸÑÿßÿ´ ÿ£ÿ≠Ÿäÿßÿ° ÿ£ÿ≥ÿπÿßÿ± ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig7)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ£ŸÇŸÑ ÿ´ŸÑÿßÿ´ ÿ£ÿ≠Ÿäÿßÿ° ÿ£ÿ≥ÿπÿßÿ± ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig8)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑŸÖÿ≥ÿßÿ®ÿ≠ ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂ ŸÑŸÉŸÑ ŸÖŸÜÿ∑ŸÇÿ©', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig9)
                                ]
                            ),
                        ])
                    ]
                ),
            ]
        ),

        html.Hr(
            style={
                'border': 'none', 
                'height': '2px', 
                'background': 'linear-gradient(to right, #020f11, #07828e)', 
                'margin': '20px 0'
            }
        ),

        # Group 2: Detailed Property Analysis
        html.Div(
            children=[
                html.H2(
                    children='ÿßŸÑÿ™ÿ≠ŸÑŸäŸÑ ÿßŸÑÿ™ŸÅÿµŸäŸÑŸä ŸÑŸÑÿπŸÇÿßÿ±ÿßÿ™',
                    style={'color': 'white', 'textAlign': 'center', 'marginBottom': '20px'}
                ),

                html.Div(
                    style={'display': 'flex', 'flexWrap': 'wrap', 'gap': '20px', 'justifyContent': 'center', 'marginTop': '30px', 'marginBottom': '30px'},
                    children=[
                        
                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿßŸÑÿπŸÑÿßŸÇÿ© ÿ®ŸäŸÜ ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ŸàÿßŸÑÿ≥ÿπÿ± ÿßŸÑÿ•ÿ¨ŸÖÿßŸÑŸä ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig4)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ™ŸàŸÅÿ± ÿßŸÑŸÖÿ≥ÿßÿ≠ÿ© ÿπÿ®ÿ± ÿßŸÑŸÖŸàÿßŸÇÿπ ŸÖŸàÿ≤ÿπÿ© ÿ≠ÿ≥ÿ® ÿ£ÿπŸÖÿßÿ± ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig6)
                                ]
                            ),
                        ]),

                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ™ÿ≥ŸÑÿ≥ŸÑ ÿßŸÑŸÖŸàÿßŸÇÿπ ŸàÿßŸÑÿ£ÿ≠Ÿäÿßÿ° ÿßŸÑÿ™Ÿä ÿ™ÿ≠ÿ™ŸàŸä ÿπŸÑŸâ ÿ£ŸÉÿ´ÿ± ŸÖŸÜ 100 ÿπŸÇÿßÿ±', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig13)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿßŸÑÿπŸÑÿßŸÇÿ© ÿ®ŸäŸÜ ÿ≥ÿπÿ± ÿßŸÑŸÖÿ±ÿ®ÿπ ŸàŸÖÿ≥ÿßÿ≠ÿ© ÿßŸÑÿπŸÇÿßÿ± ÿ≠ÿ≥ÿ® ÿßŸÑŸÖŸàŸÇÿπ', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig5)
                                ]
                            ),
                        ]),

                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ŸÖÿ™Ÿàÿ≥ÿ∑ ŸÖÿ≥ÿßÿ≠ÿ© ÿßŸÑÿπŸÇÿßÿ± (ÿ£ŸÅÿ∂ŸÑ 10 ÿ£ÿ≠Ÿäÿßÿ° ŸÅŸä ÿßŸÑÿ±Ÿäÿßÿ∂)', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig10)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ŸÖÿ™Ÿàÿ≥ÿ∑ ÿßŸÑÿ≥ÿπÿ± ÿ≠ÿ≥ÿ® ÿπŸÖÿ± ÿßŸÑÿπŸÇÿßÿ±', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig11)
                                ]
                            ),
                        ]),

                        html.Div(style={'width': '100%', 'display': 'flex', 'gap': '20px', 'justifyContent': 'center'}, children=[
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿ™Ÿàÿ≤Ÿäÿπ ÿßŸÑÿπŸÇÿßÿ±ÿßÿ™ ÿ≠ÿ≥ÿ® ŸÜŸàÿπ ÿßŸÑŸàÿßÿ¨Ÿáÿ©', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig12)
                                ]
                            ),
                            dbc.Card(
                                style={'backgroundColor': 'rgba(0,0,0,0.2)', 'padding': '10px', 'borderRadius': '15px'},
                                children=[
                                    html.H2('ÿπÿ±ÿ∂ ÿßŸÑÿ¥Ÿàÿßÿ±ÿπ ŸÅŸä ÿ¨ŸÖŸäÿπ ŸÖŸÜÿßÿ∑ŸÇ ÿßŸÑÿ±Ÿäÿßÿ∂', style={'textAlign': 'center', 'color': '#48c9b0'}),
                                    dcc.Graph(figure=fig14)
                                ]
                            ),
                        ])
                    ]
                ),
            ]
        ),
    ]
)

# Run the Dashboard

In [71]:
app.run_server(port=random.randint(1000, 5000))

Dash app running on http://127.0.0.1:3011/